// Code generated by ent, DO NOT EDIT.

package usercoupon

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usercoupon type in the database.
	Label = "user_coupon"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCouponTemplateID holds the string denoting the coupon_template_id field in the database.
	FieldCouponTemplateID = "coupon_template_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRedeemedAt holds the string denoting the redeemed_at field in the database.
	FieldRedeemedAt = "redeemed_at"
	// FieldRedeemedOrderID holds the string denoting the redeemed_order_id field in the database.
	FieldRedeemedOrderID = "redeemed_order_id"
	// FieldAppliedDiscountAmount holds the string denoting the applied_discount_amount field in the database.
	FieldAppliedDiscountAmount = "applied_discount_amount"
	// Table holds the table name of the usercoupon in the database.
	Table = "mall_user_coupons"
)

// Columns holds all SQL columns for usercoupon fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldTenantID,
	FieldUserID,
	FieldCouponTemplateID,
	FieldStatus,
	FieldRedeemedAt,
	FieldRedeemedOrderID,
	FieldAppliedDiscountAmount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-shop/app/core/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// DefaultAppliedDiscountAmount holds the default value on creation for the "applied_discount_amount" field.
	DefaultAppliedDiscountAmount int64
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusUserCouponStatusUnused  Status = "UNUSED"
	StatusUserCouponStatusUsed    Status = "USED"
	StatusUserCouponStatusExpired Status = "EXPIRED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusUserCouponStatusUnused, StatusUserCouponStatusUsed, StatusUserCouponStatusExpired:
		return nil
	default:
		return fmt.Errorf("usercoupon: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the UserCoupon queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCouponTemplateID orders the results by the coupon_template_id field.
func ByCouponTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCouponTemplateID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRedeemedAt orders the results by the redeemed_at field.
func ByRedeemedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemedAt, opts...).ToFunc()
}

// ByRedeemedOrderID orders the results by the redeemed_order_id field.
func ByRedeemedOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemedOrderID, opts...).ToFunc()
}

// ByAppliedDiscountAmount orders the results by the applied_discount_amount field.
func ByAppliedDiscountAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppliedDiscountAmount, opts...).ToFunc()
}
