// Code generated by ent, DO NOT EDIT.

package usercoupon

import (
	"go-wind-shop/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldDeletedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldTenantID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldUserID, v))
}

// CouponTemplateID applies equality check predicate on the "coupon_template_id" field. It's identical to CouponTemplateIDEQ.
func CouponTemplateID(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldCouponTemplateID, v))
}

// RedeemedAt applies equality check predicate on the "redeemed_at" field. It's identical to RedeemedAtEQ.
func RedeemedAt(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldRedeemedAt, v))
}

// RedeemedOrderID applies equality check predicate on the "redeemed_order_id" field. It's identical to RedeemedOrderIDEQ.
func RedeemedOrderID(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldRedeemedOrderID, v))
}

// AppliedDiscountAmount applies equality check predicate on the "applied_discount_amount" field. It's identical to AppliedDiscountAmountEQ.
func AppliedDiscountAmount(v int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldAppliedDiscountAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldDeletedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldTenantID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldUserID))
}

// CouponTemplateIDEQ applies the EQ predicate on the "coupon_template_id" field.
func CouponTemplateIDEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldCouponTemplateID, v))
}

// CouponTemplateIDNEQ applies the NEQ predicate on the "coupon_template_id" field.
func CouponTemplateIDNEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldCouponTemplateID, v))
}

// CouponTemplateIDIn applies the In predicate on the "coupon_template_id" field.
func CouponTemplateIDIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldCouponTemplateID, vs...))
}

// CouponTemplateIDNotIn applies the NotIn predicate on the "coupon_template_id" field.
func CouponTemplateIDNotIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldCouponTemplateID, vs...))
}

// CouponTemplateIDGT applies the GT predicate on the "coupon_template_id" field.
func CouponTemplateIDGT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldCouponTemplateID, v))
}

// CouponTemplateIDGTE applies the GTE predicate on the "coupon_template_id" field.
func CouponTemplateIDGTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldCouponTemplateID, v))
}

// CouponTemplateIDLT applies the LT predicate on the "coupon_template_id" field.
func CouponTemplateIDLT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldCouponTemplateID, v))
}

// CouponTemplateIDLTE applies the LTE predicate on the "coupon_template_id" field.
func CouponTemplateIDLTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldCouponTemplateID, v))
}

// CouponTemplateIDIsNil applies the IsNil predicate on the "coupon_template_id" field.
func CouponTemplateIDIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldCouponTemplateID))
}

// CouponTemplateIDNotNil applies the NotNil predicate on the "coupon_template_id" field.
func CouponTemplateIDNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldCouponTemplateID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldStatus))
}

// RedeemedAtEQ applies the EQ predicate on the "redeemed_at" field.
func RedeemedAtEQ(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldRedeemedAt, v))
}

// RedeemedAtNEQ applies the NEQ predicate on the "redeemed_at" field.
func RedeemedAtNEQ(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldRedeemedAt, v))
}

// RedeemedAtIn applies the In predicate on the "redeemed_at" field.
func RedeemedAtIn(vs ...time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldRedeemedAt, vs...))
}

// RedeemedAtNotIn applies the NotIn predicate on the "redeemed_at" field.
func RedeemedAtNotIn(vs ...time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldRedeemedAt, vs...))
}

// RedeemedAtGT applies the GT predicate on the "redeemed_at" field.
func RedeemedAtGT(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldRedeemedAt, v))
}

// RedeemedAtGTE applies the GTE predicate on the "redeemed_at" field.
func RedeemedAtGTE(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldRedeemedAt, v))
}

// RedeemedAtLT applies the LT predicate on the "redeemed_at" field.
func RedeemedAtLT(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldRedeemedAt, v))
}

// RedeemedAtLTE applies the LTE predicate on the "redeemed_at" field.
func RedeemedAtLTE(v time.Time) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldRedeemedAt, v))
}

// RedeemedAtIsNil applies the IsNil predicate on the "redeemed_at" field.
func RedeemedAtIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldRedeemedAt))
}

// RedeemedAtNotNil applies the NotNil predicate on the "redeemed_at" field.
func RedeemedAtNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldRedeemedAt))
}

// RedeemedOrderIDEQ applies the EQ predicate on the "redeemed_order_id" field.
func RedeemedOrderIDEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldRedeemedOrderID, v))
}

// RedeemedOrderIDNEQ applies the NEQ predicate on the "redeemed_order_id" field.
func RedeemedOrderIDNEQ(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldRedeemedOrderID, v))
}

// RedeemedOrderIDIn applies the In predicate on the "redeemed_order_id" field.
func RedeemedOrderIDIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldRedeemedOrderID, vs...))
}

// RedeemedOrderIDNotIn applies the NotIn predicate on the "redeemed_order_id" field.
func RedeemedOrderIDNotIn(vs ...uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldRedeemedOrderID, vs...))
}

// RedeemedOrderIDGT applies the GT predicate on the "redeemed_order_id" field.
func RedeemedOrderIDGT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldRedeemedOrderID, v))
}

// RedeemedOrderIDGTE applies the GTE predicate on the "redeemed_order_id" field.
func RedeemedOrderIDGTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldRedeemedOrderID, v))
}

// RedeemedOrderIDLT applies the LT predicate on the "redeemed_order_id" field.
func RedeemedOrderIDLT(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldRedeemedOrderID, v))
}

// RedeemedOrderIDLTE applies the LTE predicate on the "redeemed_order_id" field.
func RedeemedOrderIDLTE(v uint32) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldRedeemedOrderID, v))
}

// RedeemedOrderIDIsNil applies the IsNil predicate on the "redeemed_order_id" field.
func RedeemedOrderIDIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldRedeemedOrderID))
}

// RedeemedOrderIDNotNil applies the NotNil predicate on the "redeemed_order_id" field.
func RedeemedOrderIDNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldRedeemedOrderID))
}

// AppliedDiscountAmountEQ applies the EQ predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountEQ(v int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldEQ(FieldAppliedDiscountAmount, v))
}

// AppliedDiscountAmountNEQ applies the NEQ predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountNEQ(v int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNEQ(FieldAppliedDiscountAmount, v))
}

// AppliedDiscountAmountIn applies the In predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountIn(vs ...int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIn(FieldAppliedDiscountAmount, vs...))
}

// AppliedDiscountAmountNotIn applies the NotIn predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountNotIn(vs ...int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotIn(FieldAppliedDiscountAmount, vs...))
}

// AppliedDiscountAmountGT applies the GT predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountGT(v int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGT(FieldAppliedDiscountAmount, v))
}

// AppliedDiscountAmountGTE applies the GTE predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountGTE(v int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldGTE(FieldAppliedDiscountAmount, v))
}

// AppliedDiscountAmountLT applies the LT predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountLT(v int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLT(FieldAppliedDiscountAmount, v))
}

// AppliedDiscountAmountLTE applies the LTE predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountLTE(v int64) predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldLTE(FieldAppliedDiscountAmount, v))
}

// AppliedDiscountAmountIsNil applies the IsNil predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountIsNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldIsNull(FieldAppliedDiscountAmount))
}

// AppliedDiscountAmountNotNil applies the NotNil predicate on the "applied_discount_amount" field.
func AppliedDiscountAmountNotNil() predicate.UserCoupon {
	return predicate.UserCoupon(sql.FieldNotNull(FieldAppliedDiscountAmount))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserCoupon) predicate.UserCoupon {
	return predicate.UserCoupon(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserCoupon) predicate.UserCoupon {
	return predicate.UserCoupon(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserCoupon) predicate.UserCoupon {
	return predicate.UserCoupon(sql.NotPredicates(p))
}
