// Code generated by ent, DO NOT EDIT.

package invoice

import (
	"go-wind-shop/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldDeletedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTenantID, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCurrency, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldOrderID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUserID, v))
}

// InvoiceNumber applies equality check predicate on the "invoice_number" field. It's identical to InvoiceNumberEQ.
func InvoiceNumber(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceNumber, v))
}

// BuyerName applies equality check predicate on the "buyer_name" field. It's identical to BuyerNameEQ.
func BuyerName(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerName, v))
}

// BuyerTaxID applies equality check predicate on the "buyer_tax_id" field. It's identical to BuyerTaxIDEQ.
func BuyerTaxID(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerTaxID, v))
}

// BuyerAddress applies equality check predicate on the "buyer_address" field. It's identical to BuyerAddressEQ.
func BuyerAddress(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerAddress, v))
}

// BuyerPhone applies equality check predicate on the "buyer_phone" field. It's identical to BuyerPhoneEQ.
func BuyerPhone(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerPhone, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldDeletedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldTenantID))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyIsNil applies the IsNil predicate on the "currency" field.
func CurrencyIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldCurrency))
}

// CurrencyNotNil applies the NotNil predicate on the "currency" field.
func CurrencyNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldCurrency))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldCurrency, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldOrderID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint32) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldUserID))
}

// InvoiceNumberEQ applies the EQ predicate on the "invoice_number" field.
func InvoiceNumberEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceNumber, v))
}

// InvoiceNumberNEQ applies the NEQ predicate on the "invoice_number" field.
func InvoiceNumberNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldInvoiceNumber, v))
}

// InvoiceNumberIn applies the In predicate on the "invoice_number" field.
func InvoiceNumberIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldInvoiceNumber, vs...))
}

// InvoiceNumberNotIn applies the NotIn predicate on the "invoice_number" field.
func InvoiceNumberNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldInvoiceNumber, vs...))
}

// InvoiceNumberGT applies the GT predicate on the "invoice_number" field.
func InvoiceNumberGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldInvoiceNumber, v))
}

// InvoiceNumberGTE applies the GTE predicate on the "invoice_number" field.
func InvoiceNumberGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldInvoiceNumber, v))
}

// InvoiceNumberLT applies the LT predicate on the "invoice_number" field.
func InvoiceNumberLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldInvoiceNumber, v))
}

// InvoiceNumberLTE applies the LTE predicate on the "invoice_number" field.
func InvoiceNumberLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldInvoiceNumber, v))
}

// InvoiceNumberContains applies the Contains predicate on the "invoice_number" field.
func InvoiceNumberContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldInvoiceNumber, v))
}

// InvoiceNumberHasPrefix applies the HasPrefix predicate on the "invoice_number" field.
func InvoiceNumberHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldInvoiceNumber, v))
}

// InvoiceNumberHasSuffix applies the HasSuffix predicate on the "invoice_number" field.
func InvoiceNumberHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldInvoiceNumber, v))
}

// InvoiceNumberIsNil applies the IsNil predicate on the "invoice_number" field.
func InvoiceNumberIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldInvoiceNumber))
}

// InvoiceNumberNotNil applies the NotNil predicate on the "invoice_number" field.
func InvoiceNumberNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldInvoiceNumber))
}

// InvoiceNumberEqualFold applies the EqualFold predicate on the "invoice_number" field.
func InvoiceNumberEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldInvoiceNumber, v))
}

// InvoiceNumberContainsFold applies the ContainsFold predicate on the "invoice_number" field.
func InvoiceNumberContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldInvoiceNumber, v))
}

// InvoiceTypeEQ applies the EQ predicate on the "invoice_type" field.
func InvoiceTypeEQ(v InvoiceType) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceType, v))
}

// InvoiceTypeNEQ applies the NEQ predicate on the "invoice_type" field.
func InvoiceTypeNEQ(v InvoiceType) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldInvoiceType, v))
}

// InvoiceTypeIn applies the In predicate on the "invoice_type" field.
func InvoiceTypeIn(vs ...InvoiceType) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldInvoiceType, vs...))
}

// InvoiceTypeNotIn applies the NotIn predicate on the "invoice_type" field.
func InvoiceTypeNotIn(vs ...InvoiceType) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldInvoiceType, vs...))
}

// InvoiceTypeIsNil applies the IsNil predicate on the "invoice_type" field.
func InvoiceTypeIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldInvoiceType))
}

// InvoiceTypeNotNil applies the NotNil predicate on the "invoice_type" field.
func InvoiceTypeNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldInvoiceType))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldStatus))
}

// BuyerNameEQ applies the EQ predicate on the "buyer_name" field.
func BuyerNameEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerName, v))
}

// BuyerNameNEQ applies the NEQ predicate on the "buyer_name" field.
func BuyerNameNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBuyerName, v))
}

// BuyerNameIn applies the In predicate on the "buyer_name" field.
func BuyerNameIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBuyerName, vs...))
}

// BuyerNameNotIn applies the NotIn predicate on the "buyer_name" field.
func BuyerNameNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBuyerName, vs...))
}

// BuyerNameGT applies the GT predicate on the "buyer_name" field.
func BuyerNameGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldBuyerName, v))
}

// BuyerNameGTE applies the GTE predicate on the "buyer_name" field.
func BuyerNameGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldBuyerName, v))
}

// BuyerNameLT applies the LT predicate on the "buyer_name" field.
func BuyerNameLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldBuyerName, v))
}

// BuyerNameLTE applies the LTE predicate on the "buyer_name" field.
func BuyerNameLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldBuyerName, v))
}

// BuyerNameContains applies the Contains predicate on the "buyer_name" field.
func BuyerNameContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldBuyerName, v))
}

// BuyerNameHasPrefix applies the HasPrefix predicate on the "buyer_name" field.
func BuyerNameHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldBuyerName, v))
}

// BuyerNameHasSuffix applies the HasSuffix predicate on the "buyer_name" field.
func BuyerNameHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldBuyerName, v))
}

// BuyerNameIsNil applies the IsNil predicate on the "buyer_name" field.
func BuyerNameIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldBuyerName))
}

// BuyerNameNotNil applies the NotNil predicate on the "buyer_name" field.
func BuyerNameNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldBuyerName))
}

// BuyerNameEqualFold applies the EqualFold predicate on the "buyer_name" field.
func BuyerNameEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldBuyerName, v))
}

// BuyerNameContainsFold applies the ContainsFold predicate on the "buyer_name" field.
func BuyerNameContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldBuyerName, v))
}

// BuyerTaxIDEQ applies the EQ predicate on the "buyer_tax_id" field.
func BuyerTaxIDEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerTaxID, v))
}

// BuyerTaxIDNEQ applies the NEQ predicate on the "buyer_tax_id" field.
func BuyerTaxIDNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBuyerTaxID, v))
}

// BuyerTaxIDIn applies the In predicate on the "buyer_tax_id" field.
func BuyerTaxIDIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBuyerTaxID, vs...))
}

// BuyerTaxIDNotIn applies the NotIn predicate on the "buyer_tax_id" field.
func BuyerTaxIDNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBuyerTaxID, vs...))
}

// BuyerTaxIDGT applies the GT predicate on the "buyer_tax_id" field.
func BuyerTaxIDGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldBuyerTaxID, v))
}

// BuyerTaxIDGTE applies the GTE predicate on the "buyer_tax_id" field.
func BuyerTaxIDGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldBuyerTaxID, v))
}

// BuyerTaxIDLT applies the LT predicate on the "buyer_tax_id" field.
func BuyerTaxIDLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldBuyerTaxID, v))
}

// BuyerTaxIDLTE applies the LTE predicate on the "buyer_tax_id" field.
func BuyerTaxIDLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldBuyerTaxID, v))
}

// BuyerTaxIDContains applies the Contains predicate on the "buyer_tax_id" field.
func BuyerTaxIDContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldBuyerTaxID, v))
}

// BuyerTaxIDHasPrefix applies the HasPrefix predicate on the "buyer_tax_id" field.
func BuyerTaxIDHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldBuyerTaxID, v))
}

// BuyerTaxIDHasSuffix applies the HasSuffix predicate on the "buyer_tax_id" field.
func BuyerTaxIDHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldBuyerTaxID, v))
}

// BuyerTaxIDIsNil applies the IsNil predicate on the "buyer_tax_id" field.
func BuyerTaxIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldBuyerTaxID))
}

// BuyerTaxIDNotNil applies the NotNil predicate on the "buyer_tax_id" field.
func BuyerTaxIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldBuyerTaxID))
}

// BuyerTaxIDEqualFold applies the EqualFold predicate on the "buyer_tax_id" field.
func BuyerTaxIDEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldBuyerTaxID, v))
}

// BuyerTaxIDContainsFold applies the ContainsFold predicate on the "buyer_tax_id" field.
func BuyerTaxIDContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldBuyerTaxID, v))
}

// BuyerAddressEQ applies the EQ predicate on the "buyer_address" field.
func BuyerAddressEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerAddress, v))
}

// BuyerAddressNEQ applies the NEQ predicate on the "buyer_address" field.
func BuyerAddressNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBuyerAddress, v))
}

// BuyerAddressIn applies the In predicate on the "buyer_address" field.
func BuyerAddressIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBuyerAddress, vs...))
}

// BuyerAddressNotIn applies the NotIn predicate on the "buyer_address" field.
func BuyerAddressNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBuyerAddress, vs...))
}

// BuyerAddressGT applies the GT predicate on the "buyer_address" field.
func BuyerAddressGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldBuyerAddress, v))
}

// BuyerAddressGTE applies the GTE predicate on the "buyer_address" field.
func BuyerAddressGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldBuyerAddress, v))
}

// BuyerAddressLT applies the LT predicate on the "buyer_address" field.
func BuyerAddressLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldBuyerAddress, v))
}

// BuyerAddressLTE applies the LTE predicate on the "buyer_address" field.
func BuyerAddressLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldBuyerAddress, v))
}

// BuyerAddressContains applies the Contains predicate on the "buyer_address" field.
func BuyerAddressContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldBuyerAddress, v))
}

// BuyerAddressHasPrefix applies the HasPrefix predicate on the "buyer_address" field.
func BuyerAddressHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldBuyerAddress, v))
}

// BuyerAddressHasSuffix applies the HasSuffix predicate on the "buyer_address" field.
func BuyerAddressHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldBuyerAddress, v))
}

// BuyerAddressIsNil applies the IsNil predicate on the "buyer_address" field.
func BuyerAddressIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldBuyerAddress))
}

// BuyerAddressNotNil applies the NotNil predicate on the "buyer_address" field.
func BuyerAddressNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldBuyerAddress))
}

// BuyerAddressEqualFold applies the EqualFold predicate on the "buyer_address" field.
func BuyerAddressEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldBuyerAddress, v))
}

// BuyerAddressContainsFold applies the ContainsFold predicate on the "buyer_address" field.
func BuyerAddressContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldBuyerAddress, v))
}

// BuyerPhoneEQ applies the EQ predicate on the "buyer_phone" field.
func BuyerPhoneEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldBuyerPhone, v))
}

// BuyerPhoneNEQ applies the NEQ predicate on the "buyer_phone" field.
func BuyerPhoneNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldBuyerPhone, v))
}

// BuyerPhoneIn applies the In predicate on the "buyer_phone" field.
func BuyerPhoneIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldBuyerPhone, vs...))
}

// BuyerPhoneNotIn applies the NotIn predicate on the "buyer_phone" field.
func BuyerPhoneNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldBuyerPhone, vs...))
}

// BuyerPhoneGT applies the GT predicate on the "buyer_phone" field.
func BuyerPhoneGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldBuyerPhone, v))
}

// BuyerPhoneGTE applies the GTE predicate on the "buyer_phone" field.
func BuyerPhoneGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldBuyerPhone, v))
}

// BuyerPhoneLT applies the LT predicate on the "buyer_phone" field.
func BuyerPhoneLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldBuyerPhone, v))
}

// BuyerPhoneLTE applies the LTE predicate on the "buyer_phone" field.
func BuyerPhoneLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldBuyerPhone, v))
}

// BuyerPhoneContains applies the Contains predicate on the "buyer_phone" field.
func BuyerPhoneContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldBuyerPhone, v))
}

// BuyerPhoneHasPrefix applies the HasPrefix predicate on the "buyer_phone" field.
func BuyerPhoneHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldBuyerPhone, v))
}

// BuyerPhoneHasSuffix applies the HasSuffix predicate on the "buyer_phone" field.
func BuyerPhoneHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldBuyerPhone, v))
}

// BuyerPhoneIsNil applies the IsNil predicate on the "buyer_phone" field.
func BuyerPhoneIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldBuyerPhone))
}

// BuyerPhoneNotNil applies the NotNil predicate on the "buyer_phone" field.
func BuyerPhoneNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldBuyerPhone))
}

// BuyerPhoneEqualFold applies the EqualFold predicate on the "buyer_phone" field.
func BuyerPhoneEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldBuyerPhone, v))
}

// BuyerPhoneContainsFold applies the ContainsFold predicate on the "buyer_phone" field.
func BuyerPhoneContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldBuyerPhone, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldAmount, v))
}

// AmountIsNil applies the IsNil predicate on the "amount" field.
func AmountIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldAmount))
}

// AmountNotNil applies the NotNil predicate on the "amount" field.
func AmountNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldAmount))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.NotPredicates(p))
}
