// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/brandtranslation"
	"go-wind-shop/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BrandTranslationUpdate is the builder for updating BrandTranslation entities.
type BrandTranslationUpdate struct {
	config
	hooks     []Hook
	mutation  *BrandTranslationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BrandTranslationUpdate builder.
func (_u *BrandTranslationUpdate) Where(ps ...predicate.BrandTranslation) *BrandTranslationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BrandTranslationUpdate) SetUpdatedAt(v time.Time) *BrandTranslationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableUpdatedAt(v *time.Time) *BrandTranslationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *BrandTranslationUpdate) ClearUpdatedAt() *BrandTranslationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BrandTranslationUpdate) SetDeletedAt(v time.Time) *BrandTranslationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableDeletedAt(v *time.Time) *BrandTranslationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BrandTranslationUpdate) ClearDeletedAt() *BrandTranslationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BrandTranslationUpdate) SetCreatedBy(v uint32) *BrandTranslationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableCreatedBy(v *uint32) *BrandTranslationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *BrandTranslationUpdate) AddCreatedBy(v int32) *BrandTranslationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *BrandTranslationUpdate) ClearCreatedBy() *BrandTranslationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BrandTranslationUpdate) SetUpdatedBy(v uint32) *BrandTranslationUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableUpdatedBy(v *uint32) *BrandTranslationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *BrandTranslationUpdate) AddUpdatedBy(v int32) *BrandTranslationUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *BrandTranslationUpdate) ClearUpdatedBy() *BrandTranslationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *BrandTranslationUpdate) SetDeletedBy(v uint32) *BrandTranslationUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableDeletedBy(v *uint32) *BrandTranslationUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *BrandTranslationUpdate) AddDeletedBy(v int32) *BrandTranslationUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *BrandTranslationUpdate) ClearDeletedBy() *BrandTranslationUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetBrandID sets the "brand_id" field.
func (_u *BrandTranslationUpdate) SetBrandID(v uint32) *BrandTranslationUpdate {
	_u.mutation.ResetBrandID()
	_u.mutation.SetBrandID(v)
	return _u
}

// SetNillableBrandID sets the "brand_id" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableBrandID(v *uint32) *BrandTranslationUpdate {
	if v != nil {
		_u.SetBrandID(*v)
	}
	return _u
}

// AddBrandID adds value to the "brand_id" field.
func (_u *BrandTranslationUpdate) AddBrandID(v int32) *BrandTranslationUpdate {
	_u.mutation.AddBrandID(v)
	return _u
}

// ClearBrandID clears the value of the "brand_id" field.
func (_u *BrandTranslationUpdate) ClearBrandID() *BrandTranslationUpdate {
	_u.mutation.ClearBrandID()
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *BrandTranslationUpdate) SetLanguageCode(v string) *BrandTranslationUpdate {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableLanguageCode(v *string) *BrandTranslationUpdate {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// ClearLanguageCode clears the value of the "language_code" field.
func (_u *BrandTranslationUpdate) ClearLanguageCode() *BrandTranslationUpdate {
	_u.mutation.ClearLanguageCode()
	return _u
}

// SetName sets the "name" field.
func (_u *BrandTranslationUpdate) SetName(v string) *BrandTranslationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableName(v *string) *BrandTranslationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *BrandTranslationUpdate) ClearName() *BrandTranslationUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *BrandTranslationUpdate) SetSlug(v string) *BrandTranslationUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableSlug(v *string) *BrandTranslationUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *BrandTranslationUpdate) ClearSlug() *BrandTranslationUpdate {
	_u.mutation.ClearSlug()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BrandTranslationUpdate) SetDescription(v string) *BrandTranslationUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BrandTranslationUpdate) SetNillableDescription(v *string) *BrandTranslationUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BrandTranslationUpdate) ClearDescription() *BrandTranslationUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the BrandTranslationMutation object of the builder.
func (_u *BrandTranslationUpdate) Mutation() *BrandTranslationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BrandTranslationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BrandTranslationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BrandTranslationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BrandTranslationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BrandTranslationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BrandTranslationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BrandTranslationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(brandtranslation.Table, brandtranslation.Columns, sqlgraph.NewFieldSpec(brandtranslation.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(brandtranslation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(brandtranslation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(brandtranslation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(brandtranslation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(brandtranslation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(brandtranslation.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(brandtranslation.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(brandtranslation.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(brandtranslation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(brandtranslation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(brandtranslation.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(brandtranslation.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(brandtranslation.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(brandtranslation.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.BrandID(); ok {
		_spec.SetField(brandtranslation.FieldBrandID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedBrandID(); ok {
		_spec.AddField(brandtranslation.FieldBrandID, field.TypeUint32, value)
	}
	if _u.mutation.BrandIDCleared() {
		_spec.ClearField(brandtranslation.FieldBrandID, field.TypeUint32)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(brandtranslation.FieldLanguageCode, field.TypeString, value)
	}
	if _u.mutation.LanguageCodeCleared() {
		_spec.ClearField(brandtranslation.FieldLanguageCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(brandtranslation.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(brandtranslation.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(brandtranslation.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(brandtranslation.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(brandtranslation.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(brandtranslation.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{brandtranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BrandTranslationUpdateOne is the builder for updating a single BrandTranslation entity.
type BrandTranslationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BrandTranslationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BrandTranslationUpdateOne) SetUpdatedAt(v time.Time) *BrandTranslationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableUpdatedAt(v *time.Time) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *BrandTranslationUpdateOne) ClearUpdatedAt() *BrandTranslationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BrandTranslationUpdateOne) SetDeletedAt(v time.Time) *BrandTranslationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableDeletedAt(v *time.Time) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BrandTranslationUpdateOne) ClearDeletedAt() *BrandTranslationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BrandTranslationUpdateOne) SetCreatedBy(v uint32) *BrandTranslationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableCreatedBy(v *uint32) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *BrandTranslationUpdateOne) AddCreatedBy(v int32) *BrandTranslationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *BrandTranslationUpdateOne) ClearCreatedBy() *BrandTranslationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BrandTranslationUpdateOne) SetUpdatedBy(v uint32) *BrandTranslationUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableUpdatedBy(v *uint32) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *BrandTranslationUpdateOne) AddUpdatedBy(v int32) *BrandTranslationUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *BrandTranslationUpdateOne) ClearUpdatedBy() *BrandTranslationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *BrandTranslationUpdateOne) SetDeletedBy(v uint32) *BrandTranslationUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableDeletedBy(v *uint32) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *BrandTranslationUpdateOne) AddDeletedBy(v int32) *BrandTranslationUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *BrandTranslationUpdateOne) ClearDeletedBy() *BrandTranslationUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetBrandID sets the "brand_id" field.
func (_u *BrandTranslationUpdateOne) SetBrandID(v uint32) *BrandTranslationUpdateOne {
	_u.mutation.ResetBrandID()
	_u.mutation.SetBrandID(v)
	return _u
}

// SetNillableBrandID sets the "brand_id" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableBrandID(v *uint32) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetBrandID(*v)
	}
	return _u
}

// AddBrandID adds value to the "brand_id" field.
func (_u *BrandTranslationUpdateOne) AddBrandID(v int32) *BrandTranslationUpdateOne {
	_u.mutation.AddBrandID(v)
	return _u
}

// ClearBrandID clears the value of the "brand_id" field.
func (_u *BrandTranslationUpdateOne) ClearBrandID() *BrandTranslationUpdateOne {
	_u.mutation.ClearBrandID()
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *BrandTranslationUpdateOne) SetLanguageCode(v string) *BrandTranslationUpdateOne {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableLanguageCode(v *string) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// ClearLanguageCode clears the value of the "language_code" field.
func (_u *BrandTranslationUpdateOne) ClearLanguageCode() *BrandTranslationUpdateOne {
	_u.mutation.ClearLanguageCode()
	return _u
}

// SetName sets the "name" field.
func (_u *BrandTranslationUpdateOne) SetName(v string) *BrandTranslationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableName(v *string) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *BrandTranslationUpdateOne) ClearName() *BrandTranslationUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *BrandTranslationUpdateOne) SetSlug(v string) *BrandTranslationUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableSlug(v *string) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *BrandTranslationUpdateOne) ClearSlug() *BrandTranslationUpdateOne {
	_u.mutation.ClearSlug()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BrandTranslationUpdateOne) SetDescription(v string) *BrandTranslationUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BrandTranslationUpdateOne) SetNillableDescription(v *string) *BrandTranslationUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BrandTranslationUpdateOne) ClearDescription() *BrandTranslationUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the BrandTranslationMutation object of the builder.
func (_u *BrandTranslationUpdateOne) Mutation() *BrandTranslationMutation {
	return _u.mutation
}

// Where appends a list predicates to the BrandTranslationUpdate builder.
func (_u *BrandTranslationUpdateOne) Where(ps ...predicate.BrandTranslation) *BrandTranslationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BrandTranslationUpdateOne) Select(field string, fields ...string) *BrandTranslationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BrandTranslation entity.
func (_u *BrandTranslationUpdateOne) Save(ctx context.Context) (*BrandTranslation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BrandTranslationUpdateOne) SaveX(ctx context.Context) *BrandTranslation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BrandTranslationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BrandTranslationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BrandTranslationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BrandTranslationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BrandTranslationUpdateOne) sqlSave(ctx context.Context) (_node *BrandTranslation, err error) {
	_spec := sqlgraph.NewUpdateSpec(brandtranslation.Table, brandtranslation.Columns, sqlgraph.NewFieldSpec(brandtranslation.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BrandTranslation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, brandtranslation.FieldID)
		for _, f := range fields {
			if !brandtranslation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != brandtranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(brandtranslation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(brandtranslation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(brandtranslation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(brandtranslation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(brandtranslation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(brandtranslation.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(brandtranslation.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(brandtranslation.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(brandtranslation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(brandtranslation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(brandtranslation.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(brandtranslation.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(brandtranslation.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(brandtranslation.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.BrandID(); ok {
		_spec.SetField(brandtranslation.FieldBrandID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedBrandID(); ok {
		_spec.AddField(brandtranslation.FieldBrandID, field.TypeUint32, value)
	}
	if _u.mutation.BrandIDCleared() {
		_spec.ClearField(brandtranslation.FieldBrandID, field.TypeUint32)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(brandtranslation.FieldLanguageCode, field.TypeString, value)
	}
	if _u.mutation.LanguageCodeCleared() {
		_spec.ClearField(brandtranslation.FieldLanguageCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(brandtranslation.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(brandtranslation.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(brandtranslation.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(brandtranslation.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(brandtranslation.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(brandtranslation.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &BrandTranslation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{brandtranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
