// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/cart"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CartCreate is the builder for creating a Cart entity.
type CartCreate struct {
	config
	mutation *CartMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CartCreate) SetCreatedAt(v time.Time) *CartCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CartCreate) SetNillableCreatedAt(v *time.Time) *CartCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CartCreate) SetUpdatedAt(v time.Time) *CartCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CartCreate) SetNillableUpdatedAt(v *time.Time) *CartCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CartCreate) SetDeletedAt(v time.Time) *CartCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CartCreate) SetNillableDeletedAt(v *time.Time) *CartCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *CartCreate) SetCreatedBy(v uint32) *CartCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *CartCreate) SetNillableCreatedBy(v *uint32) *CartCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *CartCreate) SetUpdatedBy(v uint32) *CartCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *CartCreate) SetNillableUpdatedBy(v *uint32) *CartCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *CartCreate) SetDeletedBy(v uint32) *CartCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *CartCreate) SetNillableDeletedBy(v *uint32) *CartCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *CartCreate) SetTenantID(v uint32) *CartCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *CartCreate) SetNillableTenantID(v *uint32) *CartCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CartCreate) SetUserID(v uint32) *CartCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *CartCreate) SetNillableUserID(v *uint32) *CartCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CartCreate) SetID(v uint32) *CartCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CartMutation object of the builder.
func (_c *CartCreate) Mutation() *CartMutation {
	return _c.mutation
}

// Save creates the Cart in the database.
func (_c *CartCreate) Save(ctx context.Context) (*Cart, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CartCreate) SaveX(ctx context.Context) *Cart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CartCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CartCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CartCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := cart.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CartCreate) check() error {
	if v, ok := _c.mutation.ID(); ok {
		if err := cart.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Cart.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CartCreate) sqlSave(ctx context.Context) (*Cart, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CartCreate) createSpec() (*Cart, *sqlgraph.CreateSpec) {
	var (
		_node = &Cart{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cart.Table, sqlgraph.NewFieldSpec(cart.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cart.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cart.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(cart.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(cart.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(cart.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(cart.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(cart.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(cart.FieldUserID, field.TypeUint32, value)
		_node.UserID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Cart.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CartUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CartCreate) OnConflict(opts ...sql.ConflictOption) *CartUpsertOne {
	_c.conflict = opts
	return &CartUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Cart.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CartCreate) OnConflictColumns(columns ...string) *CartUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CartUpsertOne{
		create: _c,
	}
}

type (
	// CartUpsertOne is the builder for "upsert"-ing
	//  one Cart node.
	CartUpsertOne struct {
		create *CartCreate
	}

	// CartUpsert is the "OnConflict" setter.
	CartUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CartUpsert) SetUpdatedAt(v time.Time) *CartUpsert {
	u.Set(cart.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartUpsert) UpdateUpdatedAt() *CartUpsert {
	u.SetExcluded(cart.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CartUpsert) ClearUpdatedAt() *CartUpsert {
	u.SetNull(cart.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CartUpsert) SetDeletedAt(v time.Time) *CartUpsert {
	u.Set(cart.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CartUpsert) UpdateDeletedAt() *CartUpsert {
	u.SetExcluded(cart.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CartUpsert) ClearDeletedAt() *CartUpsert {
	u.SetNull(cart.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *CartUpsert) SetCreatedBy(v uint32) *CartUpsert {
	u.Set(cart.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CartUpsert) UpdateCreatedBy() *CartUpsert {
	u.SetExcluded(cart.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CartUpsert) AddCreatedBy(v uint32) *CartUpsert {
	u.Add(cart.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CartUpsert) ClearCreatedBy() *CartUpsert {
	u.SetNull(cart.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CartUpsert) SetUpdatedBy(v uint32) *CartUpsert {
	u.Set(cart.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CartUpsert) UpdateUpdatedBy() *CartUpsert {
	u.SetExcluded(cart.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CartUpsert) AddUpdatedBy(v uint32) *CartUpsert {
	u.Add(cart.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CartUpsert) ClearUpdatedBy() *CartUpsert {
	u.SetNull(cart.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CartUpsert) SetDeletedBy(v uint32) *CartUpsert {
	u.Set(cart.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CartUpsert) UpdateDeletedBy() *CartUpsert {
	u.SetExcluded(cart.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CartUpsert) AddDeletedBy(v uint32) *CartUpsert {
	u.Add(cart.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CartUpsert) ClearDeletedBy() *CartUpsert {
	u.SetNull(cart.FieldDeletedBy)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CartUpsert) SetUserID(v uint32) *CartUpsert {
	u.Set(cart.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CartUpsert) UpdateUserID() *CartUpsert {
	u.SetExcluded(cart.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CartUpsert) AddUserID(v uint32) *CartUpsert {
	u.Add(cart.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *CartUpsert) ClearUserID() *CartUpsert {
	u.SetNull(cart.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Cart.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(cart.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CartUpsertOne) UpdateNewValues() *CartUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(cart.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cart.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(cart.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Cart.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CartUpsertOne) Ignore() *CartUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CartUpsertOne) DoNothing() *CartUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CartCreate.OnConflict
// documentation for more info.
func (u *CartUpsertOne) Update(set func(*CartUpsert)) *CartUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CartUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CartUpsertOne) SetUpdatedAt(v time.Time) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartUpsertOne) UpdateUpdatedAt() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CartUpsertOne) ClearUpdatedAt() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CartUpsertOne) SetDeletedAt(v time.Time) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CartUpsertOne) UpdateDeletedAt() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CartUpsertOne) ClearDeletedAt() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *CartUpsertOne) SetCreatedBy(v uint32) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CartUpsertOne) AddCreatedBy(v uint32) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CartUpsertOne) UpdateCreatedBy() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CartUpsertOne) ClearCreatedBy() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CartUpsertOne) SetUpdatedBy(v uint32) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CartUpsertOne) AddUpdatedBy(v uint32) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CartUpsertOne) UpdateUpdatedBy() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CartUpsertOne) ClearUpdatedBy() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CartUpsertOne) SetDeletedBy(v uint32) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CartUpsertOne) AddDeletedBy(v uint32) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CartUpsertOne) UpdateDeletedBy() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CartUpsertOne) ClearDeletedBy() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.ClearDeletedBy()
	})
}

// SetUserID sets the "user_id" field.
func (u *CartUpsertOne) SetUserID(v uint32) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CartUpsertOne) AddUserID(v uint32) *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CartUpsertOne) UpdateUserID() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *CartUpsertOne) ClearUserID() *CartUpsertOne {
	return u.Update(func(s *CartUpsert) {
		s.ClearUserID()
	})
}

// Exec executes the query.
func (u *CartUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CartCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CartUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CartUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CartUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CartCreateBulk is the builder for creating many Cart entities in bulk.
type CartCreateBulk struct {
	config
	err      error
	builders []*CartCreate
	conflict []sql.ConflictOption
}

// Save creates the Cart entities in the database.
func (_c *CartCreateBulk) Save(ctx context.Context) ([]*Cart, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Cart, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CartCreateBulk) SaveX(ctx context.Context) []*Cart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CartCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CartCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Cart.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CartUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CartCreateBulk) OnConflict(opts ...sql.ConflictOption) *CartUpsertBulk {
	_c.conflict = opts
	return &CartUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Cart.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CartCreateBulk) OnConflictColumns(columns ...string) *CartUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CartUpsertBulk{
		create: _c,
	}
}

// CartUpsertBulk is the builder for "upsert"-ing
// a bulk of Cart nodes.
type CartUpsertBulk struct {
	create *CartCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Cart.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(cart.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CartUpsertBulk) UpdateNewValues() *CartUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(cart.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cart.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(cart.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Cart.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CartUpsertBulk) Ignore() *CartUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CartUpsertBulk) DoNothing() *CartUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CartCreateBulk.OnConflict
// documentation for more info.
func (u *CartUpsertBulk) Update(set func(*CartUpsert)) *CartUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CartUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CartUpsertBulk) SetUpdatedAt(v time.Time) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartUpsertBulk) UpdateUpdatedAt() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CartUpsertBulk) ClearUpdatedAt() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CartUpsertBulk) SetDeletedAt(v time.Time) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CartUpsertBulk) UpdateDeletedAt() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CartUpsertBulk) ClearDeletedAt() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *CartUpsertBulk) SetCreatedBy(v uint32) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CartUpsertBulk) AddCreatedBy(v uint32) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CartUpsertBulk) UpdateCreatedBy() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CartUpsertBulk) ClearCreatedBy() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CartUpsertBulk) SetUpdatedBy(v uint32) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CartUpsertBulk) AddUpdatedBy(v uint32) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CartUpsertBulk) UpdateUpdatedBy() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CartUpsertBulk) ClearUpdatedBy() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CartUpsertBulk) SetDeletedBy(v uint32) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CartUpsertBulk) AddDeletedBy(v uint32) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CartUpsertBulk) UpdateDeletedBy() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CartUpsertBulk) ClearDeletedBy() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.ClearDeletedBy()
	})
}

// SetUserID sets the "user_id" field.
func (u *CartUpsertBulk) SetUserID(v uint32) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CartUpsertBulk) AddUserID(v uint32) *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CartUpsertBulk) UpdateUserID() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *CartUpsertBulk) ClearUserID() *CartUpsertBulk {
	return u.Update(func(s *CartUpsert) {
		s.ClearUserID()
	})
}

// Exec executes the query.
func (u *CartUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CartCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CartCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CartUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
