// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-shop/app/core/service/internal/data/ent/categorytranslation"
	"go-wind-shop/app/core/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CategoryTranslationDelete is the builder for deleting a CategoryTranslation entity.
type CategoryTranslationDelete struct {
	config
	hooks    []Hook
	mutation *CategoryTranslationMutation
}

// Where appends a list predicates to the CategoryTranslationDelete builder.
func (_d *CategoryTranslationDelete) Where(ps ...predicate.CategoryTranslation) *CategoryTranslationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CategoryTranslationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CategoryTranslationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CategoryTranslationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(categorytranslation.Table, sqlgraph.NewFieldSpec(categorytranslation.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CategoryTranslationDeleteOne is the builder for deleting a single CategoryTranslation entity.
type CategoryTranslationDeleteOne struct {
	_d *CategoryTranslationDelete
}

// Where appends a list predicates to the CategoryTranslationDelete builder.
func (_d *CategoryTranslationDeleteOne) Where(ps ...predicate.CategoryTranslation) *CategoryTranslationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CategoryTranslationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{categorytranslation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CategoryTranslationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
