// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/commentlike"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentLikeCreate is the builder for creating a CommentLike entity.
type CommentLikeCreate struct {
	config
	mutation *CommentLikeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CommentLikeCreate) SetCreatedAt(v time.Time) *CommentLikeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CommentLikeCreate) SetNillableCreatedAt(v *time.Time) *CommentLikeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CommentLikeCreate) SetUpdatedAt(v time.Time) *CommentLikeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CommentLikeCreate) SetNillableUpdatedAt(v *time.Time) *CommentLikeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CommentLikeCreate) SetDeletedAt(v time.Time) *CommentLikeCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CommentLikeCreate) SetNillableDeletedAt(v *time.Time) *CommentLikeCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *CommentLikeCreate) SetTenantID(v uint32) *CommentLikeCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *CommentLikeCreate) SetNillableTenantID(v *uint32) *CommentLikeCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CommentLikeCreate) SetUserID(v uint32) *CommentLikeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *CommentLikeCreate) SetNillableUserID(v *uint32) *CommentLikeCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetCommentID sets the "comment_id" field.
func (_c *CommentLikeCreate) SetCommentID(v uint32) *CommentLikeCreate {
	_c.mutation.SetCommentID(v)
	return _c
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (_c *CommentLikeCreate) SetNillableCommentID(v *uint32) *CommentLikeCreate {
	if v != nil {
		_c.SetCommentID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CommentLikeCreate) SetID(v uint32) *CommentLikeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CommentLikeMutation object of the builder.
func (_c *CommentLikeCreate) Mutation() *CommentLikeMutation {
	return _c.mutation
}

// Save creates the CommentLike in the database.
func (_c *CommentLikeCreate) Save(ctx context.Context) (*CommentLike, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommentLikeCreate) SaveX(ctx context.Context) *CommentLike {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommentLikeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommentLikeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CommentLikeCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := commentlike.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommentLikeCreate) check() error {
	if v, ok := _c.mutation.ID(); ok {
		if err := commentlike.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CommentLike.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CommentLikeCreate) sqlSave(ctx context.Context) (*CommentLike, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommentLikeCreate) createSpec() (*CommentLike, *sqlgraph.CreateSpec) {
	var (
		_node = &CommentLike{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(commentlike.Table, sqlgraph.NewFieldSpec(commentlike.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(commentlike.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(commentlike.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(commentlike.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(commentlike.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(commentlike.FieldUserID, field.TypeUint32, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.CommentID(); ok {
		_spec.SetField(commentlike.FieldCommentID, field.TypeUint32, value)
		_node.CommentID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CommentLike.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommentLikeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CommentLikeCreate) OnConflict(opts ...sql.ConflictOption) *CommentLikeUpsertOne {
	_c.conflict = opts
	return &CommentLikeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CommentLike.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CommentLikeCreate) OnConflictColumns(columns ...string) *CommentLikeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CommentLikeUpsertOne{
		create: _c,
	}
}

type (
	// CommentLikeUpsertOne is the builder for "upsert"-ing
	//  one CommentLike node.
	CommentLikeUpsertOne struct {
		create *CommentLikeCreate
	}

	// CommentLikeUpsert is the "OnConflict" setter.
	CommentLikeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CommentLikeUpsert) SetUpdatedAt(v time.Time) *CommentLikeUpsert {
	u.Set(commentlike.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommentLikeUpsert) UpdateUpdatedAt() *CommentLikeUpsert {
	u.SetExcluded(commentlike.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CommentLikeUpsert) ClearUpdatedAt() *CommentLikeUpsert {
	u.SetNull(commentlike.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CommentLikeUpsert) SetDeletedAt(v time.Time) *CommentLikeUpsert {
	u.Set(commentlike.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CommentLikeUpsert) UpdateDeletedAt() *CommentLikeUpsert {
	u.SetExcluded(commentlike.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CommentLikeUpsert) ClearDeletedAt() *CommentLikeUpsert {
	u.SetNull(commentlike.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CommentLikeUpsert) SetUserID(v uint32) *CommentLikeUpsert {
	u.Set(commentlike.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommentLikeUpsert) UpdateUserID() *CommentLikeUpsert {
	u.SetExcluded(commentlike.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CommentLikeUpsert) AddUserID(v uint32) *CommentLikeUpsert {
	u.Add(commentlike.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *CommentLikeUpsert) ClearUserID() *CommentLikeUpsert {
	u.SetNull(commentlike.FieldUserID)
	return u
}

// SetCommentID sets the "comment_id" field.
func (u *CommentLikeUpsert) SetCommentID(v uint32) *CommentLikeUpsert {
	u.Set(commentlike.FieldCommentID, v)
	return u
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *CommentLikeUpsert) UpdateCommentID() *CommentLikeUpsert {
	u.SetExcluded(commentlike.FieldCommentID)
	return u
}

// AddCommentID adds v to the "comment_id" field.
func (u *CommentLikeUpsert) AddCommentID(v uint32) *CommentLikeUpsert {
	u.Add(commentlike.FieldCommentID, v)
	return u
}

// ClearCommentID clears the value of the "comment_id" field.
func (u *CommentLikeUpsert) ClearCommentID() *CommentLikeUpsert {
	u.SetNull(commentlike.FieldCommentID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CommentLike.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(commentlike.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CommentLikeUpsertOne) UpdateNewValues() *CommentLikeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(commentlike.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(commentlike.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(commentlike.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CommentLike.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CommentLikeUpsertOne) Ignore() *CommentLikeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommentLikeUpsertOne) DoNothing() *CommentLikeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommentLikeCreate.OnConflict
// documentation for more info.
func (u *CommentLikeUpsertOne) Update(set func(*CommentLikeUpsert)) *CommentLikeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommentLikeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CommentLikeUpsertOne) SetUpdatedAt(v time.Time) *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommentLikeUpsertOne) UpdateUpdatedAt() *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CommentLikeUpsertOne) ClearUpdatedAt() *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CommentLikeUpsertOne) SetDeletedAt(v time.Time) *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CommentLikeUpsertOne) UpdateDeletedAt() *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CommentLikeUpsertOne) ClearDeletedAt() *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CommentLikeUpsertOne) SetUserID(v uint32) *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CommentLikeUpsertOne) AddUserID(v uint32) *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommentLikeUpsertOne) UpdateUserID() *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *CommentLikeUpsertOne) ClearUserID() *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.ClearUserID()
	})
}

// SetCommentID sets the "comment_id" field.
func (u *CommentLikeUpsertOne) SetCommentID(v uint32) *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.SetCommentID(v)
	})
}

// AddCommentID adds v to the "comment_id" field.
func (u *CommentLikeUpsertOne) AddCommentID(v uint32) *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.AddCommentID(v)
	})
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *CommentLikeUpsertOne) UpdateCommentID() *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.UpdateCommentID()
	})
}

// ClearCommentID clears the value of the "comment_id" field.
func (u *CommentLikeUpsertOne) ClearCommentID() *CommentLikeUpsertOne {
	return u.Update(func(s *CommentLikeUpsert) {
		s.ClearCommentID()
	})
}

// Exec executes the query.
func (u *CommentLikeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommentLikeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommentLikeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CommentLikeUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CommentLikeUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CommentLikeCreateBulk is the builder for creating many CommentLike entities in bulk.
type CommentLikeCreateBulk struct {
	config
	err      error
	builders []*CommentLikeCreate
	conflict []sql.ConflictOption
}

// Save creates the CommentLike entities in the database.
func (_c *CommentLikeCreateBulk) Save(ctx context.Context) ([]*CommentLike, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CommentLike, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommentLikeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommentLikeCreateBulk) SaveX(ctx context.Context) []*CommentLike {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommentLikeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommentLikeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CommentLike.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommentLikeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CommentLikeCreateBulk) OnConflict(opts ...sql.ConflictOption) *CommentLikeUpsertBulk {
	_c.conflict = opts
	return &CommentLikeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CommentLike.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CommentLikeCreateBulk) OnConflictColumns(columns ...string) *CommentLikeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CommentLikeUpsertBulk{
		create: _c,
	}
}

// CommentLikeUpsertBulk is the builder for "upsert"-ing
// a bulk of CommentLike nodes.
type CommentLikeUpsertBulk struct {
	create *CommentLikeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CommentLike.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(commentlike.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CommentLikeUpsertBulk) UpdateNewValues() *CommentLikeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(commentlike.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(commentlike.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(commentlike.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CommentLike.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CommentLikeUpsertBulk) Ignore() *CommentLikeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommentLikeUpsertBulk) DoNothing() *CommentLikeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommentLikeCreateBulk.OnConflict
// documentation for more info.
func (u *CommentLikeUpsertBulk) Update(set func(*CommentLikeUpsert)) *CommentLikeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommentLikeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CommentLikeUpsertBulk) SetUpdatedAt(v time.Time) *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommentLikeUpsertBulk) UpdateUpdatedAt() *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CommentLikeUpsertBulk) ClearUpdatedAt() *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CommentLikeUpsertBulk) SetDeletedAt(v time.Time) *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CommentLikeUpsertBulk) UpdateDeletedAt() *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CommentLikeUpsertBulk) ClearDeletedAt() *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CommentLikeUpsertBulk) SetUserID(v uint32) *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CommentLikeUpsertBulk) AddUserID(v uint32) *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommentLikeUpsertBulk) UpdateUserID() *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *CommentLikeUpsertBulk) ClearUserID() *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.ClearUserID()
	})
}

// SetCommentID sets the "comment_id" field.
func (u *CommentLikeUpsertBulk) SetCommentID(v uint32) *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.SetCommentID(v)
	})
}

// AddCommentID adds v to the "comment_id" field.
func (u *CommentLikeUpsertBulk) AddCommentID(v uint32) *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.AddCommentID(v)
	})
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *CommentLikeUpsertBulk) UpdateCommentID() *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.UpdateCommentID()
	})
}

// ClearCommentID clears the value of the "comment_id" field.
func (u *CommentLikeUpsertBulk) ClearCommentID() *CommentLikeUpsertBulk {
	return u.Update(func(s *CommentLikeUpsert) {
		s.ClearCommentID()
	})
}

// Exec executes the query.
func (u *CommentLikeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CommentLikeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommentLikeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommentLikeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
