// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-shop/app/core/service/internal/data/ent/commentlike"
	"go-wind-shop/app/core/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentLikeDelete is the builder for deleting a CommentLike entity.
type CommentLikeDelete struct {
	config
	hooks    []Hook
	mutation *CommentLikeMutation
}

// Where appends a list predicates to the CommentLikeDelete builder.
func (_d *CommentLikeDelete) Where(ps ...predicate.CommentLike) *CommentLikeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CommentLikeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CommentLikeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CommentLikeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(commentlike.Table, sqlgraph.NewFieldSpec(commentlike.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CommentLikeDeleteOne is the builder for deleting a single CommentLike entity.
type CommentLikeDeleteOne struct {
	_d *CommentLikeDelete
}

// Where appends a list predicates to the CommentLikeDelete builder.
func (_d *CommentLikeDeleteOne) Where(ps ...predicate.CommentLike) *CommentLikeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CommentLikeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{commentlike.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CommentLikeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
