// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/interactioncounter"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 交互计数内聚表
type InteractionCounter struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 目标类型，对应 interaction.TargetType 枚举
	TargetType *uint8 `json:"target_type,omitempty"`
	// 目标ID
	TargetID *uint32 `json:"target_id,omitempty"`
	// 计数指标，对应 interaction.CounterMetric 枚举
	Metric *uint8 `json:"metric,omitempty"`
	// 累计计数
	Count        *int64 `json:"count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InteractionCounter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case interactioncounter.FieldID, interactioncounter.FieldTenantID, interactioncounter.FieldTargetType, interactioncounter.FieldTargetID, interactioncounter.FieldMetric, interactioncounter.FieldCount:
			values[i] = new(sql.NullInt64)
		case interactioncounter.FieldCreatedAt, interactioncounter.FieldUpdatedAt, interactioncounter.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InteractionCounter fields.
func (_m *InteractionCounter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case interactioncounter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case interactioncounter.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case interactioncounter.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case interactioncounter.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case interactioncounter.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case interactioncounter.FieldTargetType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = new(uint8)
				*_m.TargetType = uint8(value.Int64)
			}
		case interactioncounter.FieldTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = new(uint32)
				*_m.TargetID = uint32(value.Int64)
			}
		case interactioncounter.FieldMetric:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metric", values[i])
			} else if value.Valid {
				_m.Metric = new(uint8)
				*_m.Metric = uint8(value.Int64)
			}
		case interactioncounter.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = new(int64)
				*_m.Count = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InteractionCounter.
// This includes values selected through modifiers, order, etc.
func (_m *InteractionCounter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InteractionCounter.
// Note that you need to call InteractionCounter.Unwrap() before calling this method if this InteractionCounter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InteractionCounter) Update() *InteractionCounterUpdateOne {
	return NewInteractionCounterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InteractionCounter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InteractionCounter) Unwrap() *InteractionCounter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InteractionCounter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InteractionCounter) String() string {
	var builder strings.Builder
	builder.WriteString("InteractionCounter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TargetType; v != nil {
		builder.WriteString("target_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TargetID; v != nil {
		builder.WriteString("target_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Metric; v != nil {
		builder.WriteString("metric=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Count; v != nil {
		builder.WriteString("count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InteractionCounters is a parsable slice of InteractionCounter.
type InteractionCounters []*InteractionCounter
