// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/paymenttransaction"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentTransactionCreate is the builder for creating a PaymentTransaction entity.
type PaymentTransactionCreate struct {
	config
	mutation *PaymentTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentTransactionCreate) SetCreatedAt(v time.Time) *PaymentTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableCreatedAt(v *time.Time) *PaymentTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentTransactionCreate) SetUpdatedAt(v time.Time) *PaymentTransactionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableUpdatedAt(v *time.Time) *PaymentTransactionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PaymentTransactionCreate) SetDeletedAt(v time.Time) *PaymentTransactionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableDeletedAt(v *time.Time) *PaymentTransactionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PaymentTransactionCreate) SetCreatedBy(v uint32) *PaymentTransactionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableCreatedBy(v *uint32) *PaymentTransactionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PaymentTransactionCreate) SetUpdatedBy(v uint32) *PaymentTransactionCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableUpdatedBy(v *uint32) *PaymentTransactionCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *PaymentTransactionCreate) SetDeletedBy(v uint32) *PaymentTransactionCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableDeletedBy(v *uint32) *PaymentTransactionCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *PaymentTransactionCreate) SetTenantID(v uint32) *PaymentTransactionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableTenantID(v *uint32) *PaymentTransactionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentTransactionCreate) SetCurrency(v string) *PaymentTransactionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableCurrency(v *string) *PaymentTransactionCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetBusinessRefID sets the "business_ref_id" field.
func (_c *PaymentTransactionCreate) SetBusinessRefID(v string) *PaymentTransactionCreate {
	_c.mutation.SetBusinessRefID(v)
	return _c
}

// SetNillableBusinessRefID sets the "business_ref_id" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableBusinessRefID(v *string) *PaymentTransactionCreate {
	if v != nil {
		_c.SetBusinessRefID(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *PaymentTransactionCreate) SetIdempotencyKey(v string) *PaymentTransactionCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableIdempotencyKey(v *string) *PaymentTransactionCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *PaymentTransactionCreate) SetPaymentMethod(v paymenttransaction.PaymentMethod) *PaymentTransactionCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillablePaymentMethod(v *paymenttransaction.PaymentMethod) *PaymentTransactionCreate {
	if v != nil {
		_c.SetPaymentMethod(*v)
	}
	return _c
}

// SetBusinessType sets the "business_type" field.
func (_c *PaymentTransactionCreate) SetBusinessType(v paymenttransaction.BusinessType) *PaymentTransactionCreate {
	_c.mutation.SetBusinessType(v)
	return _c
}

// SetNillableBusinessType sets the "business_type" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableBusinessType(v *paymenttransaction.BusinessType) *PaymentTransactionCreate {
	if v != nil {
		_c.SetBusinessType(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *PaymentTransactionCreate) SetOrderID(v uint32) *PaymentTransactionCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableOrderID(v *uint32) *PaymentTransactionCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentTransactionCreate) SetUserID(v uint32) *PaymentTransactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableUserID(v *uint32) *PaymentTransactionCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PaymentTransactionCreate) SetAmount(v int64) *PaymentTransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableAmount(v *int64) *PaymentTransactionCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentTransactionCreate) SetStatus(v paymenttransaction.Status) *PaymentTransactionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentTransactionCreate) SetNillableStatus(v *paymenttransaction.Status) *PaymentTransactionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PaymentTransactionCreate) SetID(v uint32) *PaymentTransactionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PaymentTransactionMutation object of the builder.
func (_c *PaymentTransactionCreate) Mutation() *PaymentTransactionMutation {
	return _c.mutation
}

// Save creates the PaymentTransaction in the database.
func (_c *PaymentTransactionCreate) Save(ctx context.Context) (*PaymentTransaction, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentTransactionCreate) SaveX(ctx context.Context) *PaymentTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentTransactionCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := paymenttransaction.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := paymenttransaction.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := paymenttransaction.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentTransactionCreate) check() error {
	if v, ok := _c.mutation.PaymentMethod(); ok {
		if err := paymenttransaction.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "PaymentTransaction.payment_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BusinessType(); ok {
		if err := paymenttransaction.BusinessTypeValidator(v); err != nil {
			return &ValidationError{Name: "business_type", err: fmt.Errorf(`ent: validator failed for field "PaymentTransaction.business_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymenttransaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentTransaction.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := paymenttransaction.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PaymentTransaction.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PaymentTransactionCreate) sqlSave(ctx context.Context) (*PaymentTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentTransactionCreate) createSpec() (*PaymentTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymenttransaction.Table, sqlgraph.NewFieldSpec(paymenttransaction.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymenttransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymenttransaction.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(paymenttransaction.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(paymenttransaction.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(paymenttransaction.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(paymenttransaction.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(paymenttransaction.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(paymenttransaction.FieldCurrency, field.TypeString, value)
		_node.Currency = &value
	}
	if value, ok := _c.mutation.BusinessRefID(); ok {
		_spec.SetField(paymenttransaction.FieldBusinessRefID, field.TypeString, value)
		_node.BusinessRefID = &value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(paymenttransaction.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(paymenttransaction.FieldPaymentMethod, field.TypeEnum, value)
		_node.PaymentMethod = &value
	}
	if value, ok := _c.mutation.BusinessType(); ok {
		_spec.SetField(paymenttransaction.FieldBusinessType, field.TypeEnum, value)
		_node.BusinessType = &value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(paymenttransaction.FieldOrderID, field.TypeUint32, value)
		_node.OrderID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(paymenttransaction.FieldUserID, field.TypeUint32, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(paymenttransaction.FieldAmount, field.TypeInt64, value)
		_node.Amount = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymenttransaction.FieldStatus, field.TypeEnum, value)
		_node.Status = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentTransaction.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentTransactionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentTransactionCreate) OnConflict(opts ...sql.ConflictOption) *PaymentTransactionUpsertOne {
	_c.conflict = opts
	return &PaymentTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentTransactionCreate) OnConflictColumns(columns ...string) *PaymentTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentTransactionUpsertOne{
		create: _c,
	}
}

type (
	// PaymentTransactionUpsertOne is the builder for "upsert"-ing
	//  one PaymentTransaction node.
	PaymentTransactionUpsertOne struct {
		create *PaymentTransactionCreate
	}

	// PaymentTransactionUpsert is the "OnConflict" setter.
	PaymentTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentTransactionUpsert) SetUpdatedAt(v time.Time) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateUpdatedAt() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PaymentTransactionUpsert) ClearUpdatedAt() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentTransactionUpsert) SetDeletedAt(v time.Time) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateDeletedAt() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentTransactionUpsert) ClearDeletedAt() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *PaymentTransactionUpsert) SetCreatedBy(v uint32) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateCreatedBy() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PaymentTransactionUpsert) AddCreatedBy(v uint32) *PaymentTransactionUpsert {
	u.Add(paymenttransaction.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PaymentTransactionUpsert) ClearCreatedBy() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PaymentTransactionUpsert) SetUpdatedBy(v uint32) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateUpdatedBy() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PaymentTransactionUpsert) AddUpdatedBy(v uint32) *PaymentTransactionUpsert {
	u.Add(paymenttransaction.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PaymentTransactionUpsert) ClearUpdatedBy() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PaymentTransactionUpsert) SetDeletedBy(v uint32) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateDeletedBy() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PaymentTransactionUpsert) AddDeletedBy(v uint32) *PaymentTransactionUpsert {
	u.Add(paymenttransaction.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PaymentTransactionUpsert) ClearDeletedBy() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldDeletedBy)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PaymentTransactionUpsert) SetCurrency(v string) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateCurrency() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldCurrency)
	return u
}

// ClearCurrency clears the value of the "currency" field.
func (u *PaymentTransactionUpsert) ClearCurrency() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldCurrency)
	return u
}

// SetBusinessRefID sets the "business_ref_id" field.
func (u *PaymentTransactionUpsert) SetBusinessRefID(v string) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldBusinessRefID, v)
	return u
}

// UpdateBusinessRefID sets the "business_ref_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateBusinessRefID() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldBusinessRefID)
	return u
}

// ClearBusinessRefID clears the value of the "business_ref_id" field.
func (u *PaymentTransactionUpsert) ClearBusinessRefID() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldBusinessRefID)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *PaymentTransactionUpsert) SetIdempotencyKey(v string) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateIdempotencyKey() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *PaymentTransactionUpsert) ClearIdempotencyKey() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldIdempotencyKey)
	return u
}

// SetPaymentMethod sets the "payment_method" field.
func (u *PaymentTransactionUpsert) SetPaymentMethod(v paymenttransaction.PaymentMethod) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldPaymentMethod, v)
	return u
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdatePaymentMethod() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldPaymentMethod)
	return u
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (u *PaymentTransactionUpsert) ClearPaymentMethod() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldPaymentMethod)
	return u
}

// SetBusinessType sets the "business_type" field.
func (u *PaymentTransactionUpsert) SetBusinessType(v paymenttransaction.BusinessType) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldBusinessType, v)
	return u
}

// UpdateBusinessType sets the "business_type" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateBusinessType() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldBusinessType)
	return u
}

// ClearBusinessType clears the value of the "business_type" field.
func (u *PaymentTransactionUpsert) ClearBusinessType() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldBusinessType)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *PaymentTransactionUpsert) SetOrderID(v uint32) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateOrderID() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *PaymentTransactionUpsert) AddOrderID(v uint32) *PaymentTransactionUpsert {
	u.Add(paymenttransaction.FieldOrderID, v)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *PaymentTransactionUpsert) ClearOrderID() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldOrderID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentTransactionUpsert) SetUserID(v uint32) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateUserID() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *PaymentTransactionUpsert) AddUserID(v uint32) *PaymentTransactionUpsert {
	u.Add(paymenttransaction.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *PaymentTransactionUpsert) ClearUserID() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldUserID)
	return u
}

// SetAmount sets the "amount" field.
func (u *PaymentTransactionUpsert) SetAmount(v int64) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateAmount() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *PaymentTransactionUpsert) AddAmount(v int64) *PaymentTransactionUpsert {
	u.Add(paymenttransaction.FieldAmount, v)
	return u
}

// ClearAmount clears the value of the "amount" field.
func (u *PaymentTransactionUpsert) ClearAmount() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldAmount)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentTransactionUpsert) SetStatus(v paymenttransaction.Status) *PaymentTransactionUpsert {
	u.Set(paymenttransaction.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentTransactionUpsert) UpdateStatus() *PaymentTransactionUpsert {
	u.SetExcluded(paymenttransaction.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *PaymentTransactionUpsert) ClearStatus() *PaymentTransactionUpsert {
	u.SetNull(paymenttransaction.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PaymentTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(paymenttransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PaymentTransactionUpsertOne) UpdateNewValues() *PaymentTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(paymenttransaction.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymenttransaction.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(paymenttransaction.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentTransactionUpsertOne) Ignore() *PaymentTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentTransactionUpsertOne) DoNothing() *PaymentTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentTransactionCreate.OnConflict
// documentation for more info.
func (u *PaymentTransactionUpsertOne) Update(set func(*PaymentTransactionUpsert)) *PaymentTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentTransactionUpsertOne) SetUpdatedAt(v time.Time) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateUpdatedAt() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PaymentTransactionUpsertOne) ClearUpdatedAt() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentTransactionUpsertOne) SetDeletedAt(v time.Time) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateDeletedAt() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentTransactionUpsertOne) ClearDeletedAt() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PaymentTransactionUpsertOne) SetCreatedBy(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PaymentTransactionUpsertOne) AddCreatedBy(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateCreatedBy() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PaymentTransactionUpsertOne) ClearCreatedBy() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PaymentTransactionUpsertOne) SetUpdatedBy(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PaymentTransactionUpsertOne) AddUpdatedBy(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateUpdatedBy() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PaymentTransactionUpsertOne) ClearUpdatedBy() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PaymentTransactionUpsertOne) SetDeletedBy(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PaymentTransactionUpsertOne) AddDeletedBy(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateDeletedBy() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PaymentTransactionUpsertOne) ClearDeletedBy() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearDeletedBy()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentTransactionUpsertOne) SetCurrency(v string) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateCurrency() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateCurrency()
	})
}

// ClearCurrency clears the value of the "currency" field.
func (u *PaymentTransactionUpsertOne) ClearCurrency() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearCurrency()
	})
}

// SetBusinessRefID sets the "business_ref_id" field.
func (u *PaymentTransactionUpsertOne) SetBusinessRefID(v string) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetBusinessRefID(v)
	})
}

// UpdateBusinessRefID sets the "business_ref_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateBusinessRefID() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateBusinessRefID()
	})
}

// ClearBusinessRefID clears the value of the "business_ref_id" field.
func (u *PaymentTransactionUpsertOne) ClearBusinessRefID() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearBusinessRefID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *PaymentTransactionUpsertOne) SetIdempotencyKey(v string) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateIdempotencyKey() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *PaymentTransactionUpsertOne) ClearIdempotencyKey() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *PaymentTransactionUpsertOne) SetPaymentMethod(v paymenttransaction.PaymentMethod) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdatePaymentMethod() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdatePaymentMethod()
	})
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (u *PaymentTransactionUpsertOne) ClearPaymentMethod() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearPaymentMethod()
	})
}

// SetBusinessType sets the "business_type" field.
func (u *PaymentTransactionUpsertOne) SetBusinessType(v paymenttransaction.BusinessType) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetBusinessType(v)
	})
}

// UpdateBusinessType sets the "business_type" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateBusinessType() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateBusinessType()
	})
}

// ClearBusinessType clears the value of the "business_type" field.
func (u *PaymentTransactionUpsertOne) ClearBusinessType() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearBusinessType()
	})
}

// SetOrderID sets the "order_id" field.
func (u *PaymentTransactionUpsertOne) SetOrderID(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *PaymentTransactionUpsertOne) AddOrderID(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateOrderID() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *PaymentTransactionUpsertOne) ClearOrderID() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearOrderID()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentTransactionUpsertOne) SetUserID(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *PaymentTransactionUpsertOne) AddUserID(v uint32) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateUserID() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *PaymentTransactionUpsertOne) ClearUserID() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentTransactionUpsertOne) SetAmount(v int64) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentTransactionUpsertOne) AddAmount(v int64) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateAmount() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *PaymentTransactionUpsertOne) ClearAmount() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentTransactionUpsertOne) SetStatus(v paymenttransaction.Status) *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentTransactionUpsertOne) UpdateStatus() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *PaymentTransactionUpsertOne) ClearStatus() *PaymentTransactionUpsertOne {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *PaymentTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentTransactionUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentTransactionUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentTransactionCreateBulk is the builder for creating many PaymentTransaction entities in bulk.
type PaymentTransactionCreateBulk struct {
	config
	err      error
	builders []*PaymentTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentTransaction entities in the database.
func (_c *PaymentTransactionCreateBulk) Save(ctx context.Context) ([]*PaymentTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentTransactionCreateBulk) SaveX(ctx context.Context) []*PaymentTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentTransactionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentTransactionUpsertBulk {
	_c.conflict = opts
	return &PaymentTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentTransactionCreateBulk) OnConflictColumns(columns ...string) *PaymentTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentTransactionUpsertBulk{
		create: _c,
	}
}

// PaymentTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentTransaction nodes.
type PaymentTransactionUpsertBulk struct {
	create *PaymentTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(paymenttransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PaymentTransactionUpsertBulk) UpdateNewValues() *PaymentTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(paymenttransaction.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymenttransaction.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(paymenttransaction.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentTransactionUpsertBulk) Ignore() *PaymentTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentTransactionUpsertBulk) DoNothing() *PaymentTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentTransactionUpsertBulk) Update(set func(*PaymentTransactionUpsert)) *PaymentTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentTransactionUpsertBulk) SetUpdatedAt(v time.Time) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateUpdatedAt() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PaymentTransactionUpsertBulk) ClearUpdatedAt() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentTransactionUpsertBulk) SetDeletedAt(v time.Time) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateDeletedAt() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentTransactionUpsertBulk) ClearDeletedAt() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PaymentTransactionUpsertBulk) SetCreatedBy(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PaymentTransactionUpsertBulk) AddCreatedBy(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateCreatedBy() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PaymentTransactionUpsertBulk) ClearCreatedBy() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PaymentTransactionUpsertBulk) SetUpdatedBy(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PaymentTransactionUpsertBulk) AddUpdatedBy(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateUpdatedBy() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PaymentTransactionUpsertBulk) ClearUpdatedBy() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PaymentTransactionUpsertBulk) SetDeletedBy(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PaymentTransactionUpsertBulk) AddDeletedBy(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateDeletedBy() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PaymentTransactionUpsertBulk) ClearDeletedBy() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearDeletedBy()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentTransactionUpsertBulk) SetCurrency(v string) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateCurrency() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateCurrency()
	})
}

// ClearCurrency clears the value of the "currency" field.
func (u *PaymentTransactionUpsertBulk) ClearCurrency() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearCurrency()
	})
}

// SetBusinessRefID sets the "business_ref_id" field.
func (u *PaymentTransactionUpsertBulk) SetBusinessRefID(v string) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetBusinessRefID(v)
	})
}

// UpdateBusinessRefID sets the "business_ref_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateBusinessRefID() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateBusinessRefID()
	})
}

// ClearBusinessRefID clears the value of the "business_ref_id" field.
func (u *PaymentTransactionUpsertBulk) ClearBusinessRefID() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearBusinessRefID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *PaymentTransactionUpsertBulk) SetIdempotencyKey(v string) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateIdempotencyKey() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *PaymentTransactionUpsertBulk) ClearIdempotencyKey() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *PaymentTransactionUpsertBulk) SetPaymentMethod(v paymenttransaction.PaymentMethod) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdatePaymentMethod() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdatePaymentMethod()
	})
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (u *PaymentTransactionUpsertBulk) ClearPaymentMethod() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearPaymentMethod()
	})
}

// SetBusinessType sets the "business_type" field.
func (u *PaymentTransactionUpsertBulk) SetBusinessType(v paymenttransaction.BusinessType) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetBusinessType(v)
	})
}

// UpdateBusinessType sets the "business_type" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateBusinessType() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateBusinessType()
	})
}

// ClearBusinessType clears the value of the "business_type" field.
func (u *PaymentTransactionUpsertBulk) ClearBusinessType() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearBusinessType()
	})
}

// SetOrderID sets the "order_id" field.
func (u *PaymentTransactionUpsertBulk) SetOrderID(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *PaymentTransactionUpsertBulk) AddOrderID(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateOrderID() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *PaymentTransactionUpsertBulk) ClearOrderID() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearOrderID()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentTransactionUpsertBulk) SetUserID(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *PaymentTransactionUpsertBulk) AddUserID(v uint32) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateUserID() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *PaymentTransactionUpsertBulk) ClearUserID() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentTransactionUpsertBulk) SetAmount(v int64) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentTransactionUpsertBulk) AddAmount(v int64) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateAmount() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *PaymentTransactionUpsertBulk) ClearAmount() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentTransactionUpsertBulk) SetStatus(v paymenttransaction.Status) *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentTransactionUpsertBulk) UpdateStatus() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *PaymentTransactionUpsertBulk) ClearStatus() *PaymentTransactionUpsertBulk {
	return u.Update(func(s *PaymentTransactionUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *PaymentTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
