// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/predicate"
	"go-wind-shop/app/core/service/internal/data/ent/product"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks     []Hook
	mutation  *ProductMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductUpdate) SetUpdatedAt(v time.Time) *ProductUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableUpdatedAt(v *time.Time) *ProductUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ProductUpdate) ClearUpdatedAt() *ProductUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProductUpdate) SetDeletedAt(v time.Time) *ProductUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableDeletedAt(v *time.Time) *ProductUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProductUpdate) ClearDeletedAt() *ProductUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProductUpdate) SetCreatedBy(v uint32) *ProductUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableCreatedBy(v *uint32) *ProductUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ProductUpdate) AddCreatedBy(v int32) *ProductUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProductUpdate) ClearCreatedBy() *ProductUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProductUpdate) SetUpdatedBy(v uint32) *ProductUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableUpdatedBy(v *uint32) *ProductUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProductUpdate) AddUpdatedBy(v int32) *ProductUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProductUpdate) ClearUpdatedBy() *ProductUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ProductUpdate) SetDeletedBy(v uint32) *ProductUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableDeletedBy(v *uint32) *ProductUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ProductUpdate) AddDeletedBy(v int32) *ProductUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ProductUpdate) ClearDeletedBy() *ProductUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ProductUpdate) SetSortOrder(v uint32) *ProductUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSortOrder(v *uint32) *ProductUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ProductUpdate) AddSortOrder(v int32) *ProductUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *ProductUpdate) ClearSortOrder() *ProductUpdate {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProductUpdate) SetStatus(v product.Status) *ProductUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableStatus(v *product.Status) *ProductUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ProductUpdate) ClearStatus() *ProductUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *ProductUpdate) SetCategoryID(v uint32) *ProductUpdate {
	_u.mutation.ResetCategoryID()
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableCategoryID(v *uint32) *ProductUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// AddCategoryID adds value to the "category_id" field.
func (_u *ProductUpdate) AddCategoryID(v int32) *ProductUpdate {
	_u.mutation.AddCategoryID(v)
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *ProductUpdate) ClearCategoryID() *ProductUpdate {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetBrandID sets the "brand_id" field.
func (_u *ProductUpdate) SetBrandID(v uint32) *ProductUpdate {
	_u.mutation.ResetBrandID()
	_u.mutation.SetBrandID(v)
	return _u
}

// SetNillableBrandID sets the "brand_id" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableBrandID(v *uint32) *ProductUpdate {
	if v != nil {
		_u.SetBrandID(*v)
	}
	return _u
}

// AddBrandID adds value to the "brand_id" field.
func (_u *ProductUpdate) AddBrandID(v int32) *ProductUpdate {
	_u.mutation.AddBrandID(v)
	return _u
}

// ClearBrandID clears the value of the "brand_id" field.
func (_u *ProductUpdate) ClearBrandID() *ProductUpdate {
	_u.mutation.ClearBrandID()
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdate) Mutation() *ProductMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := product.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Product.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProductUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(product.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(product.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(product.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(product.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(product.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(product.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(product.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(product.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(product.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(product.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(product.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(product.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(product.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(product.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(product.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(product.FieldSortOrder, field.TypeUint32)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(product.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(product.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(product.FieldCategoryID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCategoryID(); ok {
		_spec.AddField(product.FieldCategoryID, field.TypeUint32, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(product.FieldCategoryID, field.TypeUint32)
	}
	if value, ok := _u.mutation.BrandID(); ok {
		_spec.SetField(product.FieldBrandID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedBrandID(); ok {
		_spec.AddField(product.FieldBrandID, field.TypeUint32, value)
	}
	if _u.mutation.BrandIDCleared() {
		_spec.ClearField(product.FieldBrandID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProductMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductUpdateOne) SetUpdatedAt(v time.Time) *ProductUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableUpdatedAt(v *time.Time) *ProductUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ProductUpdateOne) ClearUpdatedAt() *ProductUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProductUpdateOne) SetDeletedAt(v time.Time) *ProductUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableDeletedAt(v *time.Time) *ProductUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProductUpdateOne) ClearDeletedAt() *ProductUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProductUpdateOne) SetCreatedBy(v uint32) *ProductUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableCreatedBy(v *uint32) *ProductUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ProductUpdateOne) AddCreatedBy(v int32) *ProductUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProductUpdateOne) ClearCreatedBy() *ProductUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProductUpdateOne) SetUpdatedBy(v uint32) *ProductUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableUpdatedBy(v *uint32) *ProductUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProductUpdateOne) AddUpdatedBy(v int32) *ProductUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProductUpdateOne) ClearUpdatedBy() *ProductUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ProductUpdateOne) SetDeletedBy(v uint32) *ProductUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableDeletedBy(v *uint32) *ProductUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ProductUpdateOne) AddDeletedBy(v int32) *ProductUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ProductUpdateOne) ClearDeletedBy() *ProductUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ProductUpdateOne) SetSortOrder(v uint32) *ProductUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSortOrder(v *uint32) *ProductUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ProductUpdateOne) AddSortOrder(v int32) *ProductUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *ProductUpdateOne) ClearSortOrder() *ProductUpdateOne {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProductUpdateOne) SetStatus(v product.Status) *ProductUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableStatus(v *product.Status) *ProductUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ProductUpdateOne) ClearStatus() *ProductUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *ProductUpdateOne) SetCategoryID(v uint32) *ProductUpdateOne {
	_u.mutation.ResetCategoryID()
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableCategoryID(v *uint32) *ProductUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// AddCategoryID adds value to the "category_id" field.
func (_u *ProductUpdateOne) AddCategoryID(v int32) *ProductUpdateOne {
	_u.mutation.AddCategoryID(v)
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *ProductUpdateOne) ClearCategoryID() *ProductUpdateOne {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetBrandID sets the "brand_id" field.
func (_u *ProductUpdateOne) SetBrandID(v uint32) *ProductUpdateOne {
	_u.mutation.ResetBrandID()
	_u.mutation.SetBrandID(v)
	return _u
}

// SetNillableBrandID sets the "brand_id" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableBrandID(v *uint32) *ProductUpdateOne {
	if v != nil {
		_u.SetBrandID(*v)
	}
	return _u
}

// AddBrandID adds value to the "brand_id" field.
func (_u *ProductUpdateOne) AddBrandID(v int32) *ProductUpdateOne {
	_u.mutation.AddBrandID(v)
	return _u
}

// ClearBrandID clears the value of the "brand_id" field.
func (_u *ProductUpdateOne) ClearBrandID() *ProductUpdateOne {
	_u.mutation.ClearBrandID()
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdateOne) Mutation() *ProductMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Product entity.
func (_u *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := product.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Product.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProductUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(product.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(product.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(product.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(product.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(product.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(product.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(product.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(product.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(product.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(product.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(product.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(product.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(product.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(product.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(product.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(product.FieldSortOrder, field.TypeUint32)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(product.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(product.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(product.FieldCategoryID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCategoryID(); ok {
		_spec.AddField(product.FieldCategoryID, field.TypeUint32, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(product.FieldCategoryID, field.TypeUint32)
	}
	if value, ok := _u.mutation.BrandID(); ok {
		_spec.SetField(product.FieldBrandID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedBrandID(); ok {
		_spec.AddField(product.FieldBrandID, field.TypeUint32, value)
	}
	if _u.mutation.BrandIDCleared() {
		_spec.ClearField(product.FieldBrandID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Product{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
