// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/predicate"
	"go-wind-shop/app/core/service/internal/data/ent/productattributetranslation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttributeTranslationUpdate is the builder for updating ProductAttributeTranslation entities.
type ProductAttributeTranslationUpdate struct {
	config
	hooks     []Hook
	mutation  *ProductAttributeTranslationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProductAttributeTranslationUpdate builder.
func (_u *ProductAttributeTranslationUpdate) Where(ps ...predicate.ProductAttributeTranslation) *ProductAttributeTranslationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductAttributeTranslationUpdate) SetUpdatedAt(v time.Time) *ProductAttributeTranslationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdate) SetNillableUpdatedAt(v *time.Time) *ProductAttributeTranslationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ProductAttributeTranslationUpdate) ClearUpdatedAt() *ProductAttributeTranslationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProductAttributeTranslationUpdate) SetDeletedAt(v time.Time) *ProductAttributeTranslationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdate) SetNillableDeletedAt(v *time.Time) *ProductAttributeTranslationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProductAttributeTranslationUpdate) ClearDeletedAt() *ProductAttributeTranslationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProductAttributeTranslationUpdate) SetCreatedBy(v uint32) *ProductAttributeTranslationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdate) SetNillableCreatedBy(v *uint32) *ProductAttributeTranslationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ProductAttributeTranslationUpdate) AddCreatedBy(v int32) *ProductAttributeTranslationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProductAttributeTranslationUpdate) ClearCreatedBy() *ProductAttributeTranslationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProductAttributeTranslationUpdate) SetUpdatedBy(v uint32) *ProductAttributeTranslationUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdate) SetNillableUpdatedBy(v *uint32) *ProductAttributeTranslationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProductAttributeTranslationUpdate) AddUpdatedBy(v int32) *ProductAttributeTranslationUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProductAttributeTranslationUpdate) ClearUpdatedBy() *ProductAttributeTranslationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ProductAttributeTranslationUpdate) SetDeletedBy(v uint32) *ProductAttributeTranslationUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdate) SetNillableDeletedBy(v *uint32) *ProductAttributeTranslationUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ProductAttributeTranslationUpdate) AddDeletedBy(v int32) *ProductAttributeTranslationUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ProductAttributeTranslationUpdate) ClearDeletedBy() *ProductAttributeTranslationUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetAttributeID sets the "attribute_id" field.
func (_u *ProductAttributeTranslationUpdate) SetAttributeID(v uint32) *ProductAttributeTranslationUpdate {
	_u.mutation.ResetAttributeID()
	_u.mutation.SetAttributeID(v)
	return _u
}

// SetNillableAttributeID sets the "attribute_id" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdate) SetNillableAttributeID(v *uint32) *ProductAttributeTranslationUpdate {
	if v != nil {
		_u.SetAttributeID(*v)
	}
	return _u
}

// AddAttributeID adds value to the "attribute_id" field.
func (_u *ProductAttributeTranslationUpdate) AddAttributeID(v int32) *ProductAttributeTranslationUpdate {
	_u.mutation.AddAttributeID(v)
	return _u
}

// ClearAttributeID clears the value of the "attribute_id" field.
func (_u *ProductAttributeTranslationUpdate) ClearAttributeID() *ProductAttributeTranslationUpdate {
	_u.mutation.ClearAttributeID()
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *ProductAttributeTranslationUpdate) SetLanguageCode(v string) *ProductAttributeTranslationUpdate {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdate) SetNillableLanguageCode(v *string) *ProductAttributeTranslationUpdate {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// ClearLanguageCode clears the value of the "language_code" field.
func (_u *ProductAttributeTranslationUpdate) ClearLanguageCode() *ProductAttributeTranslationUpdate {
	_u.mutation.ClearLanguageCode()
	return _u
}

// SetName sets the "name" field.
func (_u *ProductAttributeTranslationUpdate) SetName(v string) *ProductAttributeTranslationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdate) SetNillableName(v *string) *ProductAttributeTranslationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ProductAttributeTranslationUpdate) ClearName() *ProductAttributeTranslationUpdate {
	_u.mutation.ClearName()
	return _u
}

// Mutation returns the ProductAttributeTranslationMutation object of the builder.
func (_u *ProductAttributeTranslationUpdate) Mutation() *ProductAttributeTranslationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductAttributeTranslationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductAttributeTranslationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductAttributeTranslationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductAttributeTranslationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProductAttributeTranslationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductAttributeTranslationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProductAttributeTranslationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(productattributetranslation.Table, productattributetranslation.Columns, sqlgraph.NewFieldSpec(productattributetranslation.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(productattributetranslation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productattributetranslation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(productattributetranslation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(productattributetranslation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(productattributetranslation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(productattributetranslation.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(productattributetranslation.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(productattributetranslation.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(productattributetranslation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(productattributetranslation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(productattributetranslation.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(productattributetranslation.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(productattributetranslation.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(productattributetranslation.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.AttributeID(); ok {
		_spec.SetField(productattributetranslation.FieldAttributeID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAttributeID(); ok {
		_spec.AddField(productattributetranslation.FieldAttributeID, field.TypeUint32, value)
	}
	if _u.mutation.AttributeIDCleared() {
		_spec.ClearField(productattributetranslation.FieldAttributeID, field.TypeUint32)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(productattributetranslation.FieldLanguageCode, field.TypeString, value)
	}
	if _u.mutation.LanguageCodeCleared() {
		_spec.ClearField(productattributetranslation.FieldLanguageCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(productattributetranslation.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(productattributetranslation.FieldName, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productattributetranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductAttributeTranslationUpdateOne is the builder for updating a single ProductAttributeTranslation entity.
type ProductAttributeTranslationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProductAttributeTranslationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductAttributeTranslationUpdateOne) SetUpdatedAt(v time.Time) *ProductAttributeTranslationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdateOne) SetNillableUpdatedAt(v *time.Time) *ProductAttributeTranslationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ProductAttributeTranslationUpdateOne) ClearUpdatedAt() *ProductAttributeTranslationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProductAttributeTranslationUpdateOne) SetDeletedAt(v time.Time) *ProductAttributeTranslationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdateOne) SetNillableDeletedAt(v *time.Time) *ProductAttributeTranslationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProductAttributeTranslationUpdateOne) ClearDeletedAt() *ProductAttributeTranslationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProductAttributeTranslationUpdateOne) SetCreatedBy(v uint32) *ProductAttributeTranslationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdateOne) SetNillableCreatedBy(v *uint32) *ProductAttributeTranslationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ProductAttributeTranslationUpdateOne) AddCreatedBy(v int32) *ProductAttributeTranslationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProductAttributeTranslationUpdateOne) ClearCreatedBy() *ProductAttributeTranslationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProductAttributeTranslationUpdateOne) SetUpdatedBy(v uint32) *ProductAttributeTranslationUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdateOne) SetNillableUpdatedBy(v *uint32) *ProductAttributeTranslationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProductAttributeTranslationUpdateOne) AddUpdatedBy(v int32) *ProductAttributeTranslationUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProductAttributeTranslationUpdateOne) ClearUpdatedBy() *ProductAttributeTranslationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ProductAttributeTranslationUpdateOne) SetDeletedBy(v uint32) *ProductAttributeTranslationUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdateOne) SetNillableDeletedBy(v *uint32) *ProductAttributeTranslationUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ProductAttributeTranslationUpdateOne) AddDeletedBy(v int32) *ProductAttributeTranslationUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ProductAttributeTranslationUpdateOne) ClearDeletedBy() *ProductAttributeTranslationUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetAttributeID sets the "attribute_id" field.
func (_u *ProductAttributeTranslationUpdateOne) SetAttributeID(v uint32) *ProductAttributeTranslationUpdateOne {
	_u.mutation.ResetAttributeID()
	_u.mutation.SetAttributeID(v)
	return _u
}

// SetNillableAttributeID sets the "attribute_id" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdateOne) SetNillableAttributeID(v *uint32) *ProductAttributeTranslationUpdateOne {
	if v != nil {
		_u.SetAttributeID(*v)
	}
	return _u
}

// AddAttributeID adds value to the "attribute_id" field.
func (_u *ProductAttributeTranslationUpdateOne) AddAttributeID(v int32) *ProductAttributeTranslationUpdateOne {
	_u.mutation.AddAttributeID(v)
	return _u
}

// ClearAttributeID clears the value of the "attribute_id" field.
func (_u *ProductAttributeTranslationUpdateOne) ClearAttributeID() *ProductAttributeTranslationUpdateOne {
	_u.mutation.ClearAttributeID()
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *ProductAttributeTranslationUpdateOne) SetLanguageCode(v string) *ProductAttributeTranslationUpdateOne {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdateOne) SetNillableLanguageCode(v *string) *ProductAttributeTranslationUpdateOne {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// ClearLanguageCode clears the value of the "language_code" field.
func (_u *ProductAttributeTranslationUpdateOne) ClearLanguageCode() *ProductAttributeTranslationUpdateOne {
	_u.mutation.ClearLanguageCode()
	return _u
}

// SetName sets the "name" field.
func (_u *ProductAttributeTranslationUpdateOne) SetName(v string) *ProductAttributeTranslationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductAttributeTranslationUpdateOne) SetNillableName(v *string) *ProductAttributeTranslationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ProductAttributeTranslationUpdateOne) ClearName() *ProductAttributeTranslationUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// Mutation returns the ProductAttributeTranslationMutation object of the builder.
func (_u *ProductAttributeTranslationUpdateOne) Mutation() *ProductAttributeTranslationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProductAttributeTranslationUpdate builder.
func (_u *ProductAttributeTranslationUpdateOne) Where(ps ...predicate.ProductAttributeTranslation) *ProductAttributeTranslationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductAttributeTranslationUpdateOne) Select(field string, fields ...string) *ProductAttributeTranslationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProductAttributeTranslation entity.
func (_u *ProductAttributeTranslationUpdateOne) Save(ctx context.Context) (*ProductAttributeTranslation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductAttributeTranslationUpdateOne) SaveX(ctx context.Context) *ProductAttributeTranslation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductAttributeTranslationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductAttributeTranslationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProductAttributeTranslationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductAttributeTranslationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProductAttributeTranslationUpdateOne) sqlSave(ctx context.Context) (_node *ProductAttributeTranslation, err error) {
	_spec := sqlgraph.NewUpdateSpec(productattributetranslation.Table, productattributetranslation.Columns, sqlgraph.NewFieldSpec(productattributetranslation.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductAttributeTranslation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productattributetranslation.FieldID)
		for _, f := range fields {
			if !productattributetranslation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productattributetranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(productattributetranslation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productattributetranslation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(productattributetranslation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(productattributetranslation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(productattributetranslation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(productattributetranslation.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(productattributetranslation.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(productattributetranslation.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(productattributetranslation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(productattributetranslation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(productattributetranslation.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(productattributetranslation.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(productattributetranslation.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(productattributetranslation.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.AttributeID(); ok {
		_spec.SetField(productattributetranslation.FieldAttributeID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAttributeID(); ok {
		_spec.AddField(productattributetranslation.FieldAttributeID, field.TypeUint32, value)
	}
	if _u.mutation.AttributeIDCleared() {
		_spec.ClearField(productattributetranslation.FieldAttributeID, field.TypeUint32)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(productattributetranslation.FieldLanguageCode, field.TypeString, value)
	}
	if _u.mutation.LanguageCodeCleared() {
		_spec.ClearField(productattributetranslation.FieldLanguageCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(productattributetranslation.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(productattributetranslation.FieldName, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ProductAttributeTranslation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productattributetranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
