// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/predicate"
	"go-wind-shop/app/core/service/internal/data/ent/skuattributecombination"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SkuAttributeCombinationUpdate is the builder for updating SkuAttributeCombination entities.
type SkuAttributeCombinationUpdate struct {
	config
	hooks     []Hook
	mutation  *SkuAttributeCombinationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SkuAttributeCombinationUpdate builder.
func (_u *SkuAttributeCombinationUpdate) Where(ps ...predicate.SkuAttributeCombination) *SkuAttributeCombinationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkuAttributeCombinationUpdate) SetUpdatedAt(v time.Time) *SkuAttributeCombinationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdate) SetNillableUpdatedAt(v *time.Time) *SkuAttributeCombinationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SkuAttributeCombinationUpdate) ClearUpdatedAt() *SkuAttributeCombinationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SkuAttributeCombinationUpdate) SetDeletedAt(v time.Time) *SkuAttributeCombinationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdate) SetNillableDeletedAt(v *time.Time) *SkuAttributeCombinationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SkuAttributeCombinationUpdate) ClearDeletedAt() *SkuAttributeCombinationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SkuAttributeCombinationUpdate) SetCreatedBy(v uint32) *SkuAttributeCombinationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdate) SetNillableCreatedBy(v *uint32) *SkuAttributeCombinationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SkuAttributeCombinationUpdate) AddCreatedBy(v int32) *SkuAttributeCombinationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SkuAttributeCombinationUpdate) ClearCreatedBy() *SkuAttributeCombinationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SkuAttributeCombinationUpdate) SetUpdatedBy(v uint32) *SkuAttributeCombinationUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdate) SetNillableUpdatedBy(v *uint32) *SkuAttributeCombinationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SkuAttributeCombinationUpdate) AddUpdatedBy(v int32) *SkuAttributeCombinationUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SkuAttributeCombinationUpdate) ClearUpdatedBy() *SkuAttributeCombinationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SkuAttributeCombinationUpdate) SetDeletedBy(v uint32) *SkuAttributeCombinationUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdate) SetNillableDeletedBy(v *uint32) *SkuAttributeCombinationUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *SkuAttributeCombinationUpdate) AddDeletedBy(v int32) *SkuAttributeCombinationUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SkuAttributeCombinationUpdate) ClearDeletedBy() *SkuAttributeCombinationUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSkuID sets the "sku_id" field.
func (_u *SkuAttributeCombinationUpdate) SetSkuID(v uint32) *SkuAttributeCombinationUpdate {
	_u.mutation.ResetSkuID()
	_u.mutation.SetSkuID(v)
	return _u
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdate) SetNillableSkuID(v *uint32) *SkuAttributeCombinationUpdate {
	if v != nil {
		_u.SetSkuID(*v)
	}
	return _u
}

// AddSkuID adds value to the "sku_id" field.
func (_u *SkuAttributeCombinationUpdate) AddSkuID(v int32) *SkuAttributeCombinationUpdate {
	_u.mutation.AddSkuID(v)
	return _u
}

// ClearSkuID clears the value of the "sku_id" field.
func (_u *SkuAttributeCombinationUpdate) ClearSkuID() *SkuAttributeCombinationUpdate {
	_u.mutation.ClearSkuID()
	return _u
}

// SetAttributeID sets the "attribute_id" field.
func (_u *SkuAttributeCombinationUpdate) SetAttributeID(v uint32) *SkuAttributeCombinationUpdate {
	_u.mutation.ResetAttributeID()
	_u.mutation.SetAttributeID(v)
	return _u
}

// SetNillableAttributeID sets the "attribute_id" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdate) SetNillableAttributeID(v *uint32) *SkuAttributeCombinationUpdate {
	if v != nil {
		_u.SetAttributeID(*v)
	}
	return _u
}

// AddAttributeID adds value to the "attribute_id" field.
func (_u *SkuAttributeCombinationUpdate) AddAttributeID(v int32) *SkuAttributeCombinationUpdate {
	_u.mutation.AddAttributeID(v)
	return _u
}

// ClearAttributeID clears the value of the "attribute_id" field.
func (_u *SkuAttributeCombinationUpdate) ClearAttributeID() *SkuAttributeCombinationUpdate {
	_u.mutation.ClearAttributeID()
	return _u
}

// SetAttributeValueID sets the "attribute_value_id" field.
func (_u *SkuAttributeCombinationUpdate) SetAttributeValueID(v uint32) *SkuAttributeCombinationUpdate {
	_u.mutation.ResetAttributeValueID()
	_u.mutation.SetAttributeValueID(v)
	return _u
}

// SetNillableAttributeValueID sets the "attribute_value_id" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdate) SetNillableAttributeValueID(v *uint32) *SkuAttributeCombinationUpdate {
	if v != nil {
		_u.SetAttributeValueID(*v)
	}
	return _u
}

// AddAttributeValueID adds value to the "attribute_value_id" field.
func (_u *SkuAttributeCombinationUpdate) AddAttributeValueID(v int32) *SkuAttributeCombinationUpdate {
	_u.mutation.AddAttributeValueID(v)
	return _u
}

// ClearAttributeValueID clears the value of the "attribute_value_id" field.
func (_u *SkuAttributeCombinationUpdate) ClearAttributeValueID() *SkuAttributeCombinationUpdate {
	_u.mutation.ClearAttributeValueID()
	return _u
}

// Mutation returns the SkuAttributeCombinationMutation object of the builder.
func (_u *SkuAttributeCombinationUpdate) Mutation() *SkuAttributeCombinationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkuAttributeCombinationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkuAttributeCombinationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkuAttributeCombinationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkuAttributeCombinationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SkuAttributeCombinationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SkuAttributeCombinationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SkuAttributeCombinationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(skuattributecombination.Table, skuattributecombination.Columns, sqlgraph.NewFieldSpec(skuattributecombination.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(skuattributecombination.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skuattributecombination.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(skuattributecombination.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(skuattributecombination.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(skuattributecombination.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(skuattributecombination.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(skuattributecombination.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(skuattributecombination.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(skuattributecombination.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(skuattributecombination.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(skuattributecombination.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(skuattributecombination.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(skuattributecombination.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(skuattributecombination.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SkuID(); ok {
		_spec.SetField(skuattributecombination.FieldSkuID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSkuID(); ok {
		_spec.AddField(skuattributecombination.FieldSkuID, field.TypeUint32, value)
	}
	if _u.mutation.SkuIDCleared() {
		_spec.ClearField(skuattributecombination.FieldSkuID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AttributeID(); ok {
		_spec.SetField(skuattributecombination.FieldAttributeID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAttributeID(); ok {
		_spec.AddField(skuattributecombination.FieldAttributeID, field.TypeUint32, value)
	}
	if _u.mutation.AttributeIDCleared() {
		_spec.ClearField(skuattributecombination.FieldAttributeID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AttributeValueID(); ok {
		_spec.SetField(skuattributecombination.FieldAttributeValueID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAttributeValueID(); ok {
		_spec.AddField(skuattributecombination.FieldAttributeValueID, field.TypeUint32, value)
	}
	if _u.mutation.AttributeValueIDCleared() {
		_spec.ClearField(skuattributecombination.FieldAttributeValueID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skuattributecombination.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkuAttributeCombinationUpdateOne is the builder for updating a single SkuAttributeCombination entity.
type SkuAttributeCombinationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SkuAttributeCombinationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkuAttributeCombinationUpdateOne) SetUpdatedAt(v time.Time) *SkuAttributeCombinationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdateOne) SetNillableUpdatedAt(v *time.Time) *SkuAttributeCombinationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SkuAttributeCombinationUpdateOne) ClearUpdatedAt() *SkuAttributeCombinationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SkuAttributeCombinationUpdateOne) SetDeletedAt(v time.Time) *SkuAttributeCombinationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdateOne) SetNillableDeletedAt(v *time.Time) *SkuAttributeCombinationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SkuAttributeCombinationUpdateOne) ClearDeletedAt() *SkuAttributeCombinationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SkuAttributeCombinationUpdateOne) SetCreatedBy(v uint32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdateOne) SetNillableCreatedBy(v *uint32) *SkuAttributeCombinationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SkuAttributeCombinationUpdateOne) AddCreatedBy(v int32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SkuAttributeCombinationUpdateOne) ClearCreatedBy() *SkuAttributeCombinationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SkuAttributeCombinationUpdateOne) SetUpdatedBy(v uint32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdateOne) SetNillableUpdatedBy(v *uint32) *SkuAttributeCombinationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SkuAttributeCombinationUpdateOne) AddUpdatedBy(v int32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SkuAttributeCombinationUpdateOne) ClearUpdatedBy() *SkuAttributeCombinationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SkuAttributeCombinationUpdateOne) SetDeletedBy(v uint32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdateOne) SetNillableDeletedBy(v *uint32) *SkuAttributeCombinationUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *SkuAttributeCombinationUpdateOne) AddDeletedBy(v int32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SkuAttributeCombinationUpdateOne) ClearDeletedBy() *SkuAttributeCombinationUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSkuID sets the "sku_id" field.
func (_u *SkuAttributeCombinationUpdateOne) SetSkuID(v uint32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.ResetSkuID()
	_u.mutation.SetSkuID(v)
	return _u
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdateOne) SetNillableSkuID(v *uint32) *SkuAttributeCombinationUpdateOne {
	if v != nil {
		_u.SetSkuID(*v)
	}
	return _u
}

// AddSkuID adds value to the "sku_id" field.
func (_u *SkuAttributeCombinationUpdateOne) AddSkuID(v int32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.AddSkuID(v)
	return _u
}

// ClearSkuID clears the value of the "sku_id" field.
func (_u *SkuAttributeCombinationUpdateOne) ClearSkuID() *SkuAttributeCombinationUpdateOne {
	_u.mutation.ClearSkuID()
	return _u
}

// SetAttributeID sets the "attribute_id" field.
func (_u *SkuAttributeCombinationUpdateOne) SetAttributeID(v uint32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.ResetAttributeID()
	_u.mutation.SetAttributeID(v)
	return _u
}

// SetNillableAttributeID sets the "attribute_id" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdateOne) SetNillableAttributeID(v *uint32) *SkuAttributeCombinationUpdateOne {
	if v != nil {
		_u.SetAttributeID(*v)
	}
	return _u
}

// AddAttributeID adds value to the "attribute_id" field.
func (_u *SkuAttributeCombinationUpdateOne) AddAttributeID(v int32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.AddAttributeID(v)
	return _u
}

// ClearAttributeID clears the value of the "attribute_id" field.
func (_u *SkuAttributeCombinationUpdateOne) ClearAttributeID() *SkuAttributeCombinationUpdateOne {
	_u.mutation.ClearAttributeID()
	return _u
}

// SetAttributeValueID sets the "attribute_value_id" field.
func (_u *SkuAttributeCombinationUpdateOne) SetAttributeValueID(v uint32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.ResetAttributeValueID()
	_u.mutation.SetAttributeValueID(v)
	return _u
}

// SetNillableAttributeValueID sets the "attribute_value_id" field if the given value is not nil.
func (_u *SkuAttributeCombinationUpdateOne) SetNillableAttributeValueID(v *uint32) *SkuAttributeCombinationUpdateOne {
	if v != nil {
		_u.SetAttributeValueID(*v)
	}
	return _u
}

// AddAttributeValueID adds value to the "attribute_value_id" field.
func (_u *SkuAttributeCombinationUpdateOne) AddAttributeValueID(v int32) *SkuAttributeCombinationUpdateOne {
	_u.mutation.AddAttributeValueID(v)
	return _u
}

// ClearAttributeValueID clears the value of the "attribute_value_id" field.
func (_u *SkuAttributeCombinationUpdateOne) ClearAttributeValueID() *SkuAttributeCombinationUpdateOne {
	_u.mutation.ClearAttributeValueID()
	return _u
}

// Mutation returns the SkuAttributeCombinationMutation object of the builder.
func (_u *SkuAttributeCombinationUpdateOne) Mutation() *SkuAttributeCombinationMutation {
	return _u.mutation
}

// Where appends a list predicates to the SkuAttributeCombinationUpdate builder.
func (_u *SkuAttributeCombinationUpdateOne) Where(ps ...predicate.SkuAttributeCombination) *SkuAttributeCombinationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkuAttributeCombinationUpdateOne) Select(field string, fields ...string) *SkuAttributeCombinationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SkuAttributeCombination entity.
func (_u *SkuAttributeCombinationUpdateOne) Save(ctx context.Context) (*SkuAttributeCombination, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkuAttributeCombinationUpdateOne) SaveX(ctx context.Context) *SkuAttributeCombination {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkuAttributeCombinationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkuAttributeCombinationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SkuAttributeCombinationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SkuAttributeCombinationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SkuAttributeCombinationUpdateOne) sqlSave(ctx context.Context) (_node *SkuAttributeCombination, err error) {
	_spec := sqlgraph.NewUpdateSpec(skuattributecombination.Table, skuattributecombination.Columns, sqlgraph.NewFieldSpec(skuattributecombination.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SkuAttributeCombination.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skuattributecombination.FieldID)
		for _, f := range fields {
			if !skuattributecombination.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skuattributecombination.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(skuattributecombination.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skuattributecombination.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(skuattributecombination.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(skuattributecombination.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(skuattributecombination.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(skuattributecombination.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(skuattributecombination.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(skuattributecombination.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(skuattributecombination.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(skuattributecombination.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(skuattributecombination.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(skuattributecombination.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(skuattributecombination.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(skuattributecombination.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SkuID(); ok {
		_spec.SetField(skuattributecombination.FieldSkuID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSkuID(); ok {
		_spec.AddField(skuattributecombination.FieldSkuID, field.TypeUint32, value)
	}
	if _u.mutation.SkuIDCleared() {
		_spec.ClearField(skuattributecombination.FieldSkuID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AttributeID(); ok {
		_spec.SetField(skuattributecombination.FieldAttributeID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAttributeID(); ok {
		_spec.AddField(skuattributecombination.FieldAttributeID, field.TypeUint32, value)
	}
	if _u.mutation.AttributeIDCleared() {
		_spec.ClearField(skuattributecombination.FieldAttributeID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AttributeValueID(); ok {
		_spec.SetField(skuattributecombination.FieldAttributeValueID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAttributeValueID(); ok {
		_spec.AddField(skuattributecombination.FieldAttributeValueID, field.TypeUint32, value)
	}
	if _u.mutation.AttributeValueIDCleared() {
		_spec.ClearField(skuattributecombination.FieldAttributeValueID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SkuAttributeCombination{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skuattributecombination.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
