// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-shop/app/core/service/internal/data/ent/predicate"
	"go-wind-shop/app/core/service/internal/data/ent/usercoupon"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCouponUpdate is the builder for updating UserCoupon entities.
type UserCouponUpdate struct {
	config
	hooks     []Hook
	mutation  *UserCouponMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserCouponUpdate builder.
func (_u *UserCouponUpdate) Where(ps ...predicate.UserCoupon) *UserCouponUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserCouponUpdate) SetUpdatedAt(v time.Time) *UserCouponUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableUpdatedAt(v *time.Time) *UserCouponUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *UserCouponUpdate) ClearUpdatedAt() *UserCouponUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserCouponUpdate) SetDeletedAt(v time.Time) *UserCouponUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableDeletedAt(v *time.Time) *UserCouponUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserCouponUpdate) ClearDeletedAt() *UserCouponUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UserCouponUpdate) SetCreatedBy(v uint32) *UserCouponUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableCreatedBy(v *uint32) *UserCouponUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *UserCouponUpdate) AddCreatedBy(v int32) *UserCouponUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *UserCouponUpdate) ClearCreatedBy() *UserCouponUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *UserCouponUpdate) SetUpdatedBy(v uint32) *UserCouponUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableUpdatedBy(v *uint32) *UserCouponUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *UserCouponUpdate) AddUpdatedBy(v int32) *UserCouponUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *UserCouponUpdate) ClearUpdatedBy() *UserCouponUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *UserCouponUpdate) SetDeletedBy(v uint32) *UserCouponUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableDeletedBy(v *uint32) *UserCouponUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *UserCouponUpdate) AddDeletedBy(v int32) *UserCouponUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *UserCouponUpdate) ClearDeletedBy() *UserCouponUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserCouponUpdate) SetUserID(v uint32) *UserCouponUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableUserID(v *uint32) *UserCouponUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserCouponUpdate) AddUserID(v int32) *UserCouponUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *UserCouponUpdate) ClearUserID() *UserCouponUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetCouponTemplateID sets the "coupon_template_id" field.
func (_u *UserCouponUpdate) SetCouponTemplateID(v uint32) *UserCouponUpdate {
	_u.mutation.ResetCouponTemplateID()
	_u.mutation.SetCouponTemplateID(v)
	return _u
}

// SetNillableCouponTemplateID sets the "coupon_template_id" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableCouponTemplateID(v *uint32) *UserCouponUpdate {
	if v != nil {
		_u.SetCouponTemplateID(*v)
	}
	return _u
}

// AddCouponTemplateID adds value to the "coupon_template_id" field.
func (_u *UserCouponUpdate) AddCouponTemplateID(v int32) *UserCouponUpdate {
	_u.mutation.AddCouponTemplateID(v)
	return _u
}

// ClearCouponTemplateID clears the value of the "coupon_template_id" field.
func (_u *UserCouponUpdate) ClearCouponTemplateID() *UserCouponUpdate {
	_u.mutation.ClearCouponTemplateID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserCouponUpdate) SetStatus(v usercoupon.Status) *UserCouponUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableStatus(v *usercoupon.Status) *UserCouponUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *UserCouponUpdate) ClearStatus() *UserCouponUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetRedeemedAt sets the "redeemed_at" field.
func (_u *UserCouponUpdate) SetRedeemedAt(v time.Time) *UserCouponUpdate {
	_u.mutation.SetRedeemedAt(v)
	return _u
}

// SetNillableRedeemedAt sets the "redeemed_at" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableRedeemedAt(v *time.Time) *UserCouponUpdate {
	if v != nil {
		_u.SetRedeemedAt(*v)
	}
	return _u
}

// ClearRedeemedAt clears the value of the "redeemed_at" field.
func (_u *UserCouponUpdate) ClearRedeemedAt() *UserCouponUpdate {
	_u.mutation.ClearRedeemedAt()
	return _u
}

// SetRedeemedOrderID sets the "redeemed_order_id" field.
func (_u *UserCouponUpdate) SetRedeemedOrderID(v uint32) *UserCouponUpdate {
	_u.mutation.ResetRedeemedOrderID()
	_u.mutation.SetRedeemedOrderID(v)
	return _u
}

// SetNillableRedeemedOrderID sets the "redeemed_order_id" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableRedeemedOrderID(v *uint32) *UserCouponUpdate {
	if v != nil {
		_u.SetRedeemedOrderID(*v)
	}
	return _u
}

// AddRedeemedOrderID adds value to the "redeemed_order_id" field.
func (_u *UserCouponUpdate) AddRedeemedOrderID(v int32) *UserCouponUpdate {
	_u.mutation.AddRedeemedOrderID(v)
	return _u
}

// ClearRedeemedOrderID clears the value of the "redeemed_order_id" field.
func (_u *UserCouponUpdate) ClearRedeemedOrderID() *UserCouponUpdate {
	_u.mutation.ClearRedeemedOrderID()
	return _u
}

// SetAppliedDiscountAmount sets the "applied_discount_amount" field.
func (_u *UserCouponUpdate) SetAppliedDiscountAmount(v int64) *UserCouponUpdate {
	_u.mutation.ResetAppliedDiscountAmount()
	_u.mutation.SetAppliedDiscountAmount(v)
	return _u
}

// SetNillableAppliedDiscountAmount sets the "applied_discount_amount" field if the given value is not nil.
func (_u *UserCouponUpdate) SetNillableAppliedDiscountAmount(v *int64) *UserCouponUpdate {
	if v != nil {
		_u.SetAppliedDiscountAmount(*v)
	}
	return _u
}

// AddAppliedDiscountAmount adds value to the "applied_discount_amount" field.
func (_u *UserCouponUpdate) AddAppliedDiscountAmount(v int64) *UserCouponUpdate {
	_u.mutation.AddAppliedDiscountAmount(v)
	return _u
}

// ClearAppliedDiscountAmount clears the value of the "applied_discount_amount" field.
func (_u *UserCouponUpdate) ClearAppliedDiscountAmount() *UserCouponUpdate {
	_u.mutation.ClearAppliedDiscountAmount()
	return _u
}

// Mutation returns the UserCouponMutation object of the builder.
func (_u *UserCouponUpdate) Mutation() *UserCouponMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserCouponUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserCouponUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserCouponUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserCouponUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserCouponUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := usercoupon.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserCoupon.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserCouponUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserCouponUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserCouponUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercoupon.Table, usercoupon.Columns, sqlgraph.NewFieldSpec(usercoupon.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(usercoupon.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usercoupon.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(usercoupon.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usercoupon.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usercoupon.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(usercoupon.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(usercoupon.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(usercoupon.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(usercoupon.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(usercoupon.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(usercoupon.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(usercoupon.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(usercoupon.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(usercoupon.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(usercoupon.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usercoupon.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usercoupon.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(usercoupon.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.CouponTemplateID(); ok {
		_spec.SetField(usercoupon.FieldCouponTemplateID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCouponTemplateID(); ok {
		_spec.AddField(usercoupon.FieldCouponTemplateID, field.TypeUint32, value)
	}
	if _u.mutation.CouponTemplateIDCleared() {
		_spec.ClearField(usercoupon.FieldCouponTemplateID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usercoupon.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(usercoupon.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.RedeemedAt(); ok {
		_spec.SetField(usercoupon.FieldRedeemedAt, field.TypeTime, value)
	}
	if _u.mutation.RedeemedAtCleared() {
		_spec.ClearField(usercoupon.FieldRedeemedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RedeemedOrderID(); ok {
		_spec.SetField(usercoupon.FieldRedeemedOrderID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRedeemedOrderID(); ok {
		_spec.AddField(usercoupon.FieldRedeemedOrderID, field.TypeUint32, value)
	}
	if _u.mutation.RedeemedOrderIDCleared() {
		_spec.ClearField(usercoupon.FieldRedeemedOrderID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AppliedDiscountAmount(); ok {
		_spec.SetField(usercoupon.FieldAppliedDiscountAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppliedDiscountAmount(); ok {
		_spec.AddField(usercoupon.FieldAppliedDiscountAmount, field.TypeInt64, value)
	}
	if _u.mutation.AppliedDiscountAmountCleared() {
		_spec.ClearField(usercoupon.FieldAppliedDiscountAmount, field.TypeInt64)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercoupon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserCouponUpdateOne is the builder for updating a single UserCoupon entity.
type UserCouponUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserCouponMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserCouponUpdateOne) SetUpdatedAt(v time.Time) *UserCouponUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableUpdatedAt(v *time.Time) *UserCouponUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *UserCouponUpdateOne) ClearUpdatedAt() *UserCouponUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserCouponUpdateOne) SetDeletedAt(v time.Time) *UserCouponUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableDeletedAt(v *time.Time) *UserCouponUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserCouponUpdateOne) ClearDeletedAt() *UserCouponUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UserCouponUpdateOne) SetCreatedBy(v uint32) *UserCouponUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableCreatedBy(v *uint32) *UserCouponUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *UserCouponUpdateOne) AddCreatedBy(v int32) *UserCouponUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *UserCouponUpdateOne) ClearCreatedBy() *UserCouponUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *UserCouponUpdateOne) SetUpdatedBy(v uint32) *UserCouponUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableUpdatedBy(v *uint32) *UserCouponUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *UserCouponUpdateOne) AddUpdatedBy(v int32) *UserCouponUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *UserCouponUpdateOne) ClearUpdatedBy() *UserCouponUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *UserCouponUpdateOne) SetDeletedBy(v uint32) *UserCouponUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableDeletedBy(v *uint32) *UserCouponUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *UserCouponUpdateOne) AddDeletedBy(v int32) *UserCouponUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *UserCouponUpdateOne) ClearDeletedBy() *UserCouponUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserCouponUpdateOne) SetUserID(v uint32) *UserCouponUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableUserID(v *uint32) *UserCouponUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserCouponUpdateOne) AddUserID(v int32) *UserCouponUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *UserCouponUpdateOne) ClearUserID() *UserCouponUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetCouponTemplateID sets the "coupon_template_id" field.
func (_u *UserCouponUpdateOne) SetCouponTemplateID(v uint32) *UserCouponUpdateOne {
	_u.mutation.ResetCouponTemplateID()
	_u.mutation.SetCouponTemplateID(v)
	return _u
}

// SetNillableCouponTemplateID sets the "coupon_template_id" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableCouponTemplateID(v *uint32) *UserCouponUpdateOne {
	if v != nil {
		_u.SetCouponTemplateID(*v)
	}
	return _u
}

// AddCouponTemplateID adds value to the "coupon_template_id" field.
func (_u *UserCouponUpdateOne) AddCouponTemplateID(v int32) *UserCouponUpdateOne {
	_u.mutation.AddCouponTemplateID(v)
	return _u
}

// ClearCouponTemplateID clears the value of the "coupon_template_id" field.
func (_u *UserCouponUpdateOne) ClearCouponTemplateID() *UserCouponUpdateOne {
	_u.mutation.ClearCouponTemplateID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserCouponUpdateOne) SetStatus(v usercoupon.Status) *UserCouponUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableStatus(v *usercoupon.Status) *UserCouponUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *UserCouponUpdateOne) ClearStatus() *UserCouponUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetRedeemedAt sets the "redeemed_at" field.
func (_u *UserCouponUpdateOne) SetRedeemedAt(v time.Time) *UserCouponUpdateOne {
	_u.mutation.SetRedeemedAt(v)
	return _u
}

// SetNillableRedeemedAt sets the "redeemed_at" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableRedeemedAt(v *time.Time) *UserCouponUpdateOne {
	if v != nil {
		_u.SetRedeemedAt(*v)
	}
	return _u
}

// ClearRedeemedAt clears the value of the "redeemed_at" field.
func (_u *UserCouponUpdateOne) ClearRedeemedAt() *UserCouponUpdateOne {
	_u.mutation.ClearRedeemedAt()
	return _u
}

// SetRedeemedOrderID sets the "redeemed_order_id" field.
func (_u *UserCouponUpdateOne) SetRedeemedOrderID(v uint32) *UserCouponUpdateOne {
	_u.mutation.ResetRedeemedOrderID()
	_u.mutation.SetRedeemedOrderID(v)
	return _u
}

// SetNillableRedeemedOrderID sets the "redeemed_order_id" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableRedeemedOrderID(v *uint32) *UserCouponUpdateOne {
	if v != nil {
		_u.SetRedeemedOrderID(*v)
	}
	return _u
}

// AddRedeemedOrderID adds value to the "redeemed_order_id" field.
func (_u *UserCouponUpdateOne) AddRedeemedOrderID(v int32) *UserCouponUpdateOne {
	_u.mutation.AddRedeemedOrderID(v)
	return _u
}

// ClearRedeemedOrderID clears the value of the "redeemed_order_id" field.
func (_u *UserCouponUpdateOne) ClearRedeemedOrderID() *UserCouponUpdateOne {
	_u.mutation.ClearRedeemedOrderID()
	return _u
}

// SetAppliedDiscountAmount sets the "applied_discount_amount" field.
func (_u *UserCouponUpdateOne) SetAppliedDiscountAmount(v int64) *UserCouponUpdateOne {
	_u.mutation.ResetAppliedDiscountAmount()
	_u.mutation.SetAppliedDiscountAmount(v)
	return _u
}

// SetNillableAppliedDiscountAmount sets the "applied_discount_amount" field if the given value is not nil.
func (_u *UserCouponUpdateOne) SetNillableAppliedDiscountAmount(v *int64) *UserCouponUpdateOne {
	if v != nil {
		_u.SetAppliedDiscountAmount(*v)
	}
	return _u
}

// AddAppliedDiscountAmount adds value to the "applied_discount_amount" field.
func (_u *UserCouponUpdateOne) AddAppliedDiscountAmount(v int64) *UserCouponUpdateOne {
	_u.mutation.AddAppliedDiscountAmount(v)
	return _u
}

// ClearAppliedDiscountAmount clears the value of the "applied_discount_amount" field.
func (_u *UserCouponUpdateOne) ClearAppliedDiscountAmount() *UserCouponUpdateOne {
	_u.mutation.ClearAppliedDiscountAmount()
	return _u
}

// Mutation returns the UserCouponMutation object of the builder.
func (_u *UserCouponUpdateOne) Mutation() *UserCouponMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserCouponUpdate builder.
func (_u *UserCouponUpdateOne) Where(ps ...predicate.UserCoupon) *UserCouponUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserCouponUpdateOne) Select(field string, fields ...string) *UserCouponUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserCoupon entity.
func (_u *UserCouponUpdateOne) Save(ctx context.Context) (*UserCoupon, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserCouponUpdateOne) SaveX(ctx context.Context) *UserCoupon {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserCouponUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserCouponUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserCouponUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := usercoupon.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserCoupon.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserCouponUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserCouponUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserCouponUpdateOne) sqlSave(ctx context.Context) (_node *UserCoupon, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercoupon.Table, usercoupon.Columns, sqlgraph.NewFieldSpec(usercoupon.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserCoupon.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usercoupon.FieldID)
		for _, f := range fields {
			if !usercoupon.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usercoupon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(usercoupon.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usercoupon.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(usercoupon.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usercoupon.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usercoupon.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(usercoupon.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(usercoupon.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(usercoupon.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(usercoupon.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(usercoupon.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(usercoupon.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(usercoupon.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(usercoupon.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(usercoupon.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(usercoupon.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usercoupon.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usercoupon.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(usercoupon.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.CouponTemplateID(); ok {
		_spec.SetField(usercoupon.FieldCouponTemplateID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCouponTemplateID(); ok {
		_spec.AddField(usercoupon.FieldCouponTemplateID, field.TypeUint32, value)
	}
	if _u.mutation.CouponTemplateIDCleared() {
		_spec.ClearField(usercoupon.FieldCouponTemplateID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usercoupon.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(usercoupon.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.RedeemedAt(); ok {
		_spec.SetField(usercoupon.FieldRedeemedAt, field.TypeTime, value)
	}
	if _u.mutation.RedeemedAtCleared() {
		_spec.ClearField(usercoupon.FieldRedeemedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RedeemedOrderID(); ok {
		_spec.SetField(usercoupon.FieldRedeemedOrderID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRedeemedOrderID(); ok {
		_spec.AddField(usercoupon.FieldRedeemedOrderID, field.TypeUint32, value)
	}
	if _u.mutation.RedeemedOrderIDCleared() {
		_spec.ClearField(usercoupon.FieldRedeemedOrderID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AppliedDiscountAmount(); ok {
		_spec.SetField(usercoupon.FieldAppliedDiscountAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppliedDiscountAmount(); ok {
		_spec.AddField(usercoupon.FieldAppliedDiscountAmount, field.TypeInt64, value)
	}
	if _u.mutation.AppliedDiscountAmountCleared() {
		_spec.ClearField(usercoupon.FieldAppliedDiscountAmount, field.TypeInt64)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserCoupon{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercoupon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
