syntax = "proto3";

package app.service.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "pagination/v1/pagination.proto";

import "order/service/v1/order.proto";

// 订单前台服务
service OrderService {
  rpc List (pagination.PagingRequest) returns (order.service.v1.ListOrderResponse) {
    option (google.api.http) = {
      get: "/app/v1/mall/orders"
    };
  }

  rpc Count (pagination.PagingRequest) returns (order.service.v1.CountOrderResponse) {
    option (google.api.http) = {
      get: "/app/v1/mall/orders/count"
    };
  }

  rpc Get (order.service.v1.GetOrderRequest) returns (order.service.v1.Order) {
    option (google.api.http) = {
      get: "/app/v1/mall/orders/{id}"
    };
  }

  rpc Create (order.service.v1.CreateOrderRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/app/v1/mall/orders"
      body: "*"
    };
  }

  rpc Update (order.service.v1.UpdateOrderRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/app/v1/mall/orders/{id}"
      body: "*"
    };
  }

  rpc Delete (order.service.v1.DeleteOrderRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/app/v1/mall/orders"
    };
  }
}

// 订单项前台服务
service OrderItemService {
  rpc List (pagination.PagingRequest) returns (order.service.v1.ListOrderItemResponse) {
    option (google.api.http) = {
      get: "/app/v1/mall/order-items"
    };
  }

  rpc Count (pagination.PagingRequest) returns (order.service.v1.CountOrderItemResponse) {
    option (google.api.http) = {
      get: "/app/v1/mall/order-items/count"
    };
  }

  rpc Get (order.service.v1.GetOrderItemRequest) returns (order.service.v1.OrderItem) {
    option (google.api.http) = {
      get: "/app/v1/mall/order-items/{id}"
    };
  }

  rpc Create (order.service.v1.CreateOrderItemRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/app/v1/mall/order-items"
      body: "*"
    };
  }

  rpc BatchCreate (order.service.v1.BatchCreateOrderItemsRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/app/v1/mall/order-items/batch"
      body: "*"
    };
  }

  rpc Update (order.service.v1.UpdateOrderItemRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/app/v1/mall/order-items/{id}"
      body: "*"
    };
  }

  rpc Delete (order.service.v1.DeleteOrderItemRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/app/v1/mall/order-items"
    };
  }
}
