// Code generated by ent, DO NOT EDIT.

package productattributevalue

import (
	"go-wind-shop/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldDeletedBy, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldSortOrder, v))
}

// AttributeID applies equality check predicate on the "attribute_id" field. It's identical to AttributeIDEQ.
func AttributeID(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldAttributeID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotNull(FieldDeletedBy))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldSortOrder, v))
}

// SortOrderIsNil applies the IsNil predicate on the "sort_order" field.
func SortOrderIsNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIsNull(FieldSortOrder))
}

// SortOrderNotNil applies the NotNil predicate on the "sort_order" field.
func SortOrderNotNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotNull(FieldSortOrder))
}

// AttributeIDEQ applies the EQ predicate on the "attribute_id" field.
func AttributeIDEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldEQ(FieldAttributeID, v))
}

// AttributeIDNEQ applies the NEQ predicate on the "attribute_id" field.
func AttributeIDNEQ(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNEQ(FieldAttributeID, v))
}

// AttributeIDIn applies the In predicate on the "attribute_id" field.
func AttributeIDIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIn(FieldAttributeID, vs...))
}

// AttributeIDNotIn applies the NotIn predicate on the "attribute_id" field.
func AttributeIDNotIn(vs ...uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotIn(FieldAttributeID, vs...))
}

// AttributeIDGT applies the GT predicate on the "attribute_id" field.
func AttributeIDGT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGT(FieldAttributeID, v))
}

// AttributeIDGTE applies the GTE predicate on the "attribute_id" field.
func AttributeIDGTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldGTE(FieldAttributeID, v))
}

// AttributeIDLT applies the LT predicate on the "attribute_id" field.
func AttributeIDLT(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLT(FieldAttributeID, v))
}

// AttributeIDLTE applies the LTE predicate on the "attribute_id" field.
func AttributeIDLTE(v uint32) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldLTE(FieldAttributeID, v))
}

// AttributeIDIsNil applies the IsNil predicate on the "attribute_id" field.
func AttributeIDIsNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldIsNull(FieldAttributeID))
}

// AttributeIDNotNil applies the NotNil predicate on the "attribute_id" field.
func AttributeIDNotNil() predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.FieldNotNull(FieldAttributeID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductAttributeValue) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductAttributeValue) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductAttributeValue) predicate.ProductAttributeValue {
	return predicate.ProductAttributeValue(sql.NotPredicates(p))
}
